// AUTO-GENERATED by scripts/buildIdahoUnits.mjs — do not edit by hand.
// Idaho GMU "basics": centroid + elk zone + geo description for every unit.
// Source: Idaho Fish & Game Game Units GIS. Re-run the script to refresh.

export type IdahoUnit = {
  unit: string;
  elkZone: string | null;
  coords: { lat: number; lng: number };
  description: string;
};

export const IDAHO_GMU_UNITS: Record<string, IdahoUnit> = {
  "1": {
    "unit": "1",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 48.54315,
      "lng": -116.54409
    },
    "description": "Idaho Game Management Unit 1, in the Panhandle elk zone."
  },
  "2": {
    "unit": "2",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 47.97588,
      "lng": -116.6988
    },
    "description": "Idaho Game Management Unit 2, in the Panhandle elk zone."
  },
  "3": {
    "unit": "3",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 47.66054,
      "lng": -116.54575
    },
    "description": "Idaho Game Management Unit 3, in the Panhandle elk zone."
  },
  "4": {
    "unit": "4",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 47.7206,
      "lng": -116.1439
    },
    "description": "Idaho Game Management Unit 4, in the Panhandle elk zone."
  },
  "5": {
    "unit": "5",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 47.37448,
      "lng": -116.76141
    },
    "description": "Idaho Game Management Unit 5, in the Panhandle elk zone."
  },
  "6": {
    "unit": "6",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 47.17301,
      "lng": -116.20903
    },
    "description": "Idaho Game Management Unit 6, in the Panhandle elk zone."
  },
  "7": {
    "unit": "7",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 47.18765,
      "lng": -115.47558
    },
    "description": "Idaho Game Management Unit 7, in the Panhandle elk zone."
  },
  "8": {
    "unit": "8",
    "elkZone": "Palouse",
    "coords": {
      "lat": 46.77389,
      "lng": -116.68071
    },
    "description": "Idaho Game Management Unit 8, in the Palouse elk zone."
  },
  "9": {
    "unit": "9",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 47.03678,
      "lng": -115.67035
    },
    "description": "Idaho Game Management Unit 9, in the Panhandle elk zone."
  },
  "10": {
    "unit": "10",
    "elkZone": "Lolo",
    "coords": {
      "lat": 46.7145,
      "lng": -115.33647
    },
    "description": "Idaho Game Management Unit 10, in the Lolo elk zone."
  },
  "11": {
    "unit": "11",
    "elkZone": "Hells Canyon",
    "coords": {
      "lat": 46.15119,
      "lng": -116.7021
    },
    "description": "Idaho Game Management Unit 11, in the Hells Canyon elk zone."
  },
  "12": {
    "unit": "12",
    "elkZone": "Lolo",
    "coords": {
      "lat": 46.437,
      "lng": -115.03677
    },
    "description": "Idaho Game Management Unit 12, in the Lolo elk zone."
  },
  "13": {
    "unit": "13",
    "elkZone": "Hells Canyon",
    "coords": {
      "lat": 45.83438,
      "lng": -116.54561
    },
    "description": "Idaho Game Management Unit 13, in the Hells Canyon elk zone."
  },
  "14": {
    "unit": "14",
    "elkZone": "Elk City",
    "coords": {
      "lat": 45.72239,
      "lng": -116.11934
    },
    "description": "Idaho Game Management Unit 14, in the Elk City elk zone."
  },
  "15": {
    "unit": "15",
    "elkZone": "Elk City",
    "coords": {
      "lat": 45.8081,
      "lng": -115.63032
    },
    "description": "Idaho Game Management Unit 15, in the Elk City elk zone."
  },
  "16": {
    "unit": "16",
    "elkZone": "Elk City",
    "coords": {
      "lat": 46.05737,
      "lng": -115.58233
    },
    "description": "Idaho Game Management Unit 16, in the Elk City elk zone."
  },
  "17": {
    "unit": "17",
    "elkZone": "Selway",
    "coords": {
      "lat": 45.92422,
      "lng": -114.85039
    },
    "description": "Idaho Game Management Unit 17, in the Selway elk zone."
  },
  "18": {
    "unit": "18",
    "elkZone": "Hells Canyon",
    "coords": {
      "lat": 45.46733,
      "lng": -116.46358
    },
    "description": "Idaho Game Management Unit 18, in the Hells Canyon elk zone."
  },
  "19": {
    "unit": "19",
    "elkZone": "Selway",
    "coords": {
      "lat": 45.5233,
      "lng": -115.69015
    },
    "description": "Idaho Game Management Unit 19, in the Selway elk zone."
  },
  "20": {
    "unit": "20",
    "elkZone": "Selway",
    "coords": {
      "lat": 45.59495,
      "lng": -115.15065
    },
    "description": "Idaho Game Management Unit 20, in the Selway elk zone."
  },
  "21": {
    "unit": "21",
    "elkZone": "Salmon",
    "coords": {
      "lat": 45.50084,
      "lng": -114.36442
    },
    "description": "Idaho Game Management Unit 21, in the Salmon elk zone."
  },
  "22": {
    "unit": "22",
    "elkZone": "Weiser River",
    "coords": {
      "lat": 44.95637,
      "lng": -116.64355
    },
    "description": "Idaho Game Management Unit 22, in the Weiser River elk zone."
  },
  "23": {
    "unit": "23",
    "elkZone": "McCall",
    "coords": {
      "lat": 45.10462,
      "lng": -116.23625
    },
    "description": "Idaho Game Management Unit 23, in the McCall elk zone."
  },
  "24": {
    "unit": "24",
    "elkZone": "McCall",
    "coords": {
      "lat": 44.72463,
      "lng": -115.99627
    },
    "description": "Idaho Game Management Unit 24, in the McCall elk zone."
  },
  "25": {
    "unit": "25",
    "elkZone": "McCall",
    "coords": {
      "lat": 44.80021,
      "lng": -115.59671
    },
    "description": "Idaho Game Management Unit 25, in the McCall elk zone."
  },
  "26": {
    "unit": "26",
    "elkZone": "Middle Fork",
    "coords": {
      "lat": 45.09111,
      "lng": -115.10072
    },
    "description": "Idaho Game Management Unit 26, in the Middle Fork elk zone."
  },
  "27": {
    "unit": "27",
    "elkZone": "Middle Fork",
    "coords": {
      "lat": 44.86436,
      "lng": -114.92885
    },
    "description": "Idaho Game Management Unit 27, in the Middle Fork elk zone."
  },
  "28": {
    "unit": "28",
    "elkZone": "Salmon",
    "coords": {
      "lat": 45.03606,
      "lng": -114.27313
    },
    "description": "Idaho Game Management Unit 28, in the Salmon elk zone."
  },
  "29": {
    "unit": "29",
    "elkZone": "Lemhi",
    "coords": {
      "lat": 44.7839,
      "lng": -113.60197
    },
    "description": "Idaho Game Management Unit 29, in the Lemhi elk zone."
  },
  "30": {
    "unit": "30",
    "elkZone": "Beaverhead",
    "coords": {
      "lat": 44.9775,
      "lng": -113.57282
    },
    "description": "Idaho Game Management Unit 30, in the Beaverhead elk zone."
  },
  "31": {
    "unit": "31",
    "elkZone": "Brownlee",
    "coords": {
      "lat": 44.53717,
      "lng": -116.95999
    },
    "description": "Idaho Game Management Unit 31, in the Brownlee elk zone."
  },
  "32": {
    "unit": "32",
    "elkZone": "Weiser River",
    "coords": {
      "lat": 44.15725,
      "lng": -116.54841
    },
    "description": "Idaho Game Management Unit 32, in the Weiser River elk zone."
  },
  "33": {
    "unit": "33",
    "elkZone": "Sawtooth",
    "coords": {
      "lat": 44.26409,
      "lng": -115.75221
    },
    "description": "Idaho Game Management Unit 33, in the Sawtooth elk zone."
  },
  "34": {
    "unit": "34",
    "elkZone": "Sawtooth",
    "coords": {
      "lat": 44.41695,
      "lng": -115.49541
    },
    "description": "Idaho Game Management Unit 34, in the Sawtooth elk zone."
  },
  "35": {
    "unit": "35",
    "elkZone": "Boise River",
    "coords": {
      "lat": 44.14572,
      "lng": -115.28109
    },
    "description": "Idaho Game Management Unit 35, in the Boise River elk zone."
  },
  "36": {
    "unit": "36",
    "elkZone": "Sawtooth",
    "coords": {
      "lat": 44.16862,
      "lng": -114.88743
    },
    "description": "Idaho Game Management Unit 36, in the Sawtooth elk zone."
  },
  "37": {
    "unit": "37",
    "elkZone": "Lemhi",
    "coords": {
      "lat": 44.37911,
      "lng": -113.86564
    },
    "description": "Idaho Game Management Unit 37, in the Lemhi elk zone."
  },
  "38": {
    "unit": "38",
    "elkZone": "Owyhee",
    "coords": {
      "lat": 43.5132,
      "lng": -116.3495
    },
    "description": "Idaho Game Management Unit 38, in the Owyhee elk zone."
  },
  "39": {
    "unit": "39",
    "elkZone": "Boise River",
    "coords": {
      "lat": 43.61864,
      "lng": -115.64611
    },
    "description": "Idaho Game Management Unit 39, in the Boise River elk zone."
  },
  "40": {
    "unit": "40",
    "elkZone": "Owyhee",
    "coords": {
      "lat": 43.09465,
      "lng": -116.55189
    },
    "description": "Idaho Game Management Unit 40, in the Owyhee elk zone."
  },
  "41": {
    "unit": "41",
    "elkZone": "Owyhee",
    "coords": {
      "lat": 42.49891,
      "lng": -116.09842
    },
    "description": "Idaho Game Management Unit 41, in the Owyhee elk zone."
  },
  "42": {
    "unit": "42",
    "elkZone": "Owyhee",
    "coords": {
      "lat": 42.35339,
      "lng": -116.62705
    },
    "description": "Idaho Game Management Unit 42, in the Owyhee elk zone."
  },
  "43": {
    "unit": "43",
    "elkZone": "Smoky - Bennett",
    "coords": {
      "lat": 43.62799,
      "lng": -115.05814
    },
    "description": "Idaho Game Management Unit 43, in the Smoky - Bennett elk zone."
  },
  "44": {
    "unit": "44",
    "elkZone": "Smoky - Bennett",
    "coords": {
      "lat": 43.45198,
      "lng": -114.95542
    },
    "description": "Idaho Game Management Unit 44, in the Smoky - Bennett elk zone."
  },
  "45": {
    "unit": "45",
    "elkZone": "Smoky - Bennett",
    "coords": {
      "lat": 43.13311,
      "lng": -115.21182
    },
    "description": "Idaho Game Management Unit 45, in the Smoky - Bennett elk zone."
  },
  "46": {
    "unit": "46",
    "elkZone": "South Hills",
    "coords": {
      "lat": 42.49953,
      "lng": -115.19635
    },
    "description": "Idaho Game Management Unit 46, in the South Hills elk zone."
  },
  "47": {
    "unit": "47",
    "elkZone": "South Hills",
    "coords": {
      "lat": 42.10908,
      "lng": -115.00303
    },
    "description": "Idaho Game Management Unit 47, in the South Hills elk zone."
  },
  "48": {
    "unit": "48",
    "elkZone": "Smoky - Bennett",
    "coords": {
      "lat": 43.62525,
      "lng": -114.4856
    },
    "description": "Idaho Game Management Unit 48, in the Smoky - Bennett elk zone."
  },
  "49": {
    "unit": "49",
    "elkZone": "Pioneer",
    "coords": {
      "lat": 43.55825,
      "lng": -114.0123
    },
    "description": "Idaho Game Management Unit 49, in the Pioneer elk zone."
  },
  "50": {
    "unit": "50",
    "elkZone": "Pioneer",
    "coords": {
      "lat": 43.82983,
      "lng": -113.74829
    },
    "description": "Idaho Game Management Unit 50, in the Pioneer elk zone."
  },
  "51": {
    "unit": "51",
    "elkZone": "Lemhi",
    "coords": {
      "lat": 44.0645,
      "lng": -113.2619
    },
    "description": "Idaho Game Management Unit 51, in the Lemhi elk zone."
  },
  "52": {
    "unit": "52",
    "elkZone": "Smoky - Bennett",
    "coords": {
      "lat": 43.13307,
      "lng": -114.32957
    },
    "description": "Idaho Game Management Unit 52, in the Smoky - Bennett elk zone."
  },
  "53": {
    "unit": "53",
    "elkZone": "Big Desert",
    "coords": {
      "lat": 42.71497,
      "lng": -114.16997
    },
    "description": "Idaho Game Management Unit 53, in the Big Desert elk zone."
  },
  "54": {
    "unit": "54",
    "elkZone": "South Hills",
    "coords": {
      "lat": 42.27837,
      "lng": -114.24071
    },
    "description": "Idaho Game Management Unit 54, in the South Hills elk zone."
  },
  "55": {
    "unit": "55",
    "elkZone": "South Hills",
    "coords": {
      "lat": 42.26418,
      "lng": -113.59093
    },
    "description": "Idaho Game Management Unit 55, in the South Hills elk zone."
  },
  "56": {
    "unit": "56",
    "elkZone": "South Hills",
    "coords": {
      "lat": 42.37407,
      "lng": -113.08651
    },
    "description": "Idaho Game Management Unit 56, in the South Hills elk zone."
  },
  "57": {
    "unit": "57",
    "elkZone": "South Hills",
    "coords": {
      "lat": 42.25565,
      "lng": -113.12945
    },
    "description": "Idaho Game Management Unit 57, in the South Hills elk zone."
  },
  "58": {
    "unit": "58",
    "elkZone": "Beaverhead",
    "coords": {
      "lat": 44.1328,
      "lng": -113.00934
    },
    "description": "Idaho Game Management Unit 58, in the Beaverhead elk zone."
  },
  "59": {
    "unit": "59",
    "elkZone": "Beaverhead",
    "coords": {
      "lat": 44.36479,
      "lng": -112.48031
    },
    "description": "Idaho Game Management Unit 59, in the Beaverhead elk zone."
  },
  "60": {
    "unit": "60",
    "elkZone": "Island Park",
    "coords": {
      "lat": 44.21972,
      "lng": -111.63931
    },
    "description": "Idaho Game Management Unit 60, in the Island Park elk zone."
  },
  "61": {
    "unit": "61",
    "elkZone": "Island Park",
    "coords": {
      "lat": 44.52036,
      "lng": -111.70323
    },
    "description": "Idaho Game Management Unit 61, in the Island Park elk zone."
  },
  "62": {
    "unit": "62",
    "elkZone": "Island Park",
    "coords": {
      "lat": 43.99128,
      "lng": -111.39816
    },
    "description": "Idaho Game Management Unit 62, in the Island Park elk zone."
  },
  "63": {
    "unit": "63",
    "elkZone": "Snake River",
    "coords": {
      "lat": 43.68755,
      "lng": -112.61002
    },
    "description": "Idaho Game Management Unit 63, in the Snake River elk zone."
  },
  "64": {
    "unit": "64",
    "elkZone": "Palisades",
    "coords": {
      "lat": 43.75673,
      "lng": -111.55075
    },
    "description": "Idaho Game Management Unit 64, in the Palisades elk zone."
  },
  "65": {
    "unit": "65",
    "elkZone": "Palisades",
    "coords": {
      "lat": 43.70195,
      "lng": -111.20644
    },
    "description": "Idaho Game Management Unit 65, in the Palisades elk zone."
  },
  "66": {
    "unit": "66",
    "elkZone": "Tex Creek",
    "coords": {
      "lat": 43.31041,
      "lng": -111.31446
    },
    "description": "Idaho Game Management Unit 66, in the Tex Creek elk zone."
  },
  "67": {
    "unit": "67",
    "elkZone": "Palisades",
    "coords": {
      "lat": 43.41781,
      "lng": -111.3543
    },
    "description": "Idaho Game Management Unit 67, in the Palisades elk zone."
  },
  "68": {
    "unit": "68",
    "elkZone": "Big Desert",
    "coords": {
      "lat": 43.12053,
      "lng": -112.92007
    },
    "description": "Idaho Game Management Unit 68, in the Big Desert elk zone."
  },
  "69": {
    "unit": "69",
    "elkZone": "Tex Creek",
    "coords": {
      "lat": 43.26248,
      "lng": -111.91437
    },
    "description": "Idaho Game Management Unit 69, in the Tex Creek elk zone."
  },
  "70": {
    "unit": "70",
    "elkZone": "Bannock",
    "coords": {
      "lat": 42.73771,
      "lng": -112.40655
    },
    "description": "Idaho Game Management Unit 70, in the Bannock elk zone."
  },
  "71": {
    "unit": "71",
    "elkZone": "Bannock",
    "coords": {
      "lat": 42.83179,
      "lng": -112.16162
    },
    "description": "Idaho Game Management Unit 71, in the Bannock elk zone."
  },
  "72": {
    "unit": "72",
    "elkZone": "Bannock",
    "coords": {
      "lat": 42.85302,
      "lng": -111.75876
    },
    "description": "Idaho Game Management Unit 72, in the Bannock elk zone."
  },
  "73": {
    "unit": "73",
    "elkZone": "Bannock",
    "coords": {
      "lat": 42.30581,
      "lng": -112.25238
    },
    "description": "Idaho Game Management Unit 73, in the Bannock elk zone."
  },
  "74": {
    "unit": "74",
    "elkZone": "Bannock",
    "coords": {
      "lat": 42.43941,
      "lng": -111.96139
    },
    "description": "Idaho Game Management Unit 74, in the Bannock elk zone."
  },
  "75": {
    "unit": "75",
    "elkZone": "Bear River",
    "coords": {
      "lat": 42.47519,
      "lng": -111.5143
    },
    "description": "Idaho Game Management Unit 75, in the Bear River elk zone."
  },
  "76": {
    "unit": "76",
    "elkZone": "Diamond Creek",
    "coords": {
      "lat": 42.50556,
      "lng": -111.31934
    },
    "description": "Idaho Game Management Unit 76, in the Diamond Creek elk zone."
  },
  "77": {
    "unit": "77",
    "elkZone": "Bear River",
    "coords": {
      "lat": 42.18588,
      "lng": -111.71478
    },
    "description": "Idaho Game Management Unit 77, in the Bear River elk zone."
  },
  "78": {
    "unit": "78",
    "elkZone": "Bear River",
    "coords": {
      "lat": 42.18617,
      "lng": -111.50424
    },
    "description": "Idaho Game Management Unit 78, in the Bear River elk zone."
  },
  "4A": {
    "unit": "4A",
    "elkZone": "Panhandle",
    "coords": {
      "lat": 48.10916,
      "lng": -116.31435
    },
    "description": "Idaho Game Management Unit 4A, in the Panhandle elk zone."
  },
  "8A": {
    "unit": "8A",
    "elkZone": "Palouse",
    "coords": {
      "lat": 46.79821,
      "lng": -116.52164
    },
    "description": "Idaho Game Management Unit 8A, in the Palouse elk zone."
  },
  "10A": {
    "unit": "10A",
    "elkZone": "Dworshak",
    "coords": {
      "lat": 46.58217,
      "lng": -115.8931
    },
    "description": "Idaho Game Management Unit 10A, in the Dworshak elk zone."
  },
  "11A": {
    "unit": "11A",
    "elkZone": "Palouse",
    "coords": {
      "lat": 46.22518,
      "lng": -116.40185
    },
    "description": "Idaho Game Management Unit 11A, in the Palouse elk zone."
  },
  "16A": {
    "unit": "16A",
    "elkZone": "Selway",
    "coords": {
      "lat": 45.89149,
      "lng": -115.227
    },
    "description": "Idaho Game Management Unit 16A, in the Selway elk zone."
  },
  "19A": {
    "unit": "19A",
    "elkZone": "McCall",
    "coords": {
      "lat": 45.2697,
      "lng": -115.75405
    },
    "description": "Idaho Game Management Unit 19A, in the McCall elk zone."
  },
  "20A": {
    "unit": "20A",
    "elkZone": "Middle Fork",
    "coords": {
      "lat": 45.31114,
      "lng": -115.11038
    },
    "description": "Idaho Game Management Unit 20A, in the Middle Fork elk zone."
  },
  "21A": {
    "unit": "21A",
    "elkZone": "Salmon",
    "coords": {
      "lat": 45.45976,
      "lng": -113.83738
    },
    "description": "Idaho Game Management Unit 21A, in the Salmon elk zone."
  },
  "30A": {
    "unit": "30A",
    "elkZone": "Beaverhead",
    "coords": {
      "lat": 44.62545,
      "lng": -113.17803
    },
    "description": "Idaho Game Management Unit 30A, in the Beaverhead elk zone."
  },
  "32A": {
    "unit": "32A",
    "elkZone": "Weiser River",
    "coords": {
      "lat": 44.5247,
      "lng": -116.2613
    },
    "description": "Idaho Game Management Unit 32A, in the Weiser River elk zone."
  },
  "36A": {
    "unit": "36A",
    "elkZone": "Pioneer",
    "coords": {
      "lat": 44.15769,
      "lng": -114.34375
    },
    "description": "Idaho Game Management Unit 36A, in the Pioneer elk zone."
  },
  "36B": {
    "unit": "36B",
    "elkZone": "Salmon",
    "coords": {
      "lat": 44.56204,
      "lng": -114.40149
    },
    "description": "Idaho Game Management Unit 36B, in the Salmon elk zone."
  },
  "37A": {
    "unit": "37A",
    "elkZone": "Lemhi",
    "coords": {
      "lat": 44.59965,
      "lng": -113.75208
    },
    "description": "Idaho Game Management Unit 37A, in the Lemhi elk zone."
  },
  "52A": {
    "unit": "52A",
    "elkZone": "Big Desert",
    "coords": {
      "lat": 43.17929,
      "lng": -113.81265
    },
    "description": "Idaho Game Management Unit 52A, in the Big Desert elk zone."
  },
  "59A": {
    "unit": "59A",
    "elkZone": "Beaverhead",
    "coords": {
      "lat": 44.23315,
      "lng": -112.60867
    },
    "description": "Idaho Game Management Unit 59A, in the Beaverhead elk zone."
  },
  "60A": {
    "unit": "60A",
    "elkZone": "Island Park",
    "coords": {
      "lat": 44.09274,
      "lng": -111.93349
    },
    "description": "Idaho Game Management Unit 60A, in the Island Park elk zone."
  },
  "62A": {
    "unit": "62A",
    "elkZone": "Island Park",
    "coords": {
      "lat": 44.20778,
      "lng": -111.28357
    },
    "description": "Idaho Game Management Unit 62A, in the Island Park elk zone."
  },
  "63A": {
    "unit": "63A",
    "elkZone": "Snake River",
    "coords": {
      "lat": 43.66086,
      "lng": -111.92684
    },
    "description": "Idaho Game Management Unit 63A, in the Snake River elk zone."
  },
  "66A": {
    "unit": "66A",
    "elkZone": "Diamond Creek",
    "coords": {
      "lat": 43.07431,
      "lng": -111.27536
    },
    "description": "Idaho Game Management Unit 66A, in the Diamond Creek elk zone."
  },
  "68A": {
    "unit": "68A",
    "elkZone": "Big Desert",
    "coords": {
      "lat": 43.1379,
      "lng": -112.46702
    },
    "description": "Idaho Game Management Unit 68A, in the Big Desert elk zone."
  },
  "73A": {
    "unit": "73A",
    "elkZone": "Bannock",
    "coords": {
      "lat": 42.52827,
      "lng": -112.71928
    },
    "description": "Idaho Game Management Unit 73A, in the Bannock elk zone."
  },
  "YNP": {
    "unit": "YNP",
    "elkZone": null,
    "coords": {
      "lat": 44.30971,
      "lng": -111.07327
    },
    "description": "Idaho Game Management Unit YNP."
  }
};
