// AUTO-GENERATED by scripts/buildMontanaDraw.mjs — do not edit by hand.
// Montana limited-permit DRAW SUCCESS (2026) from MT FWP reports.
// General deer/elk licenses are general/OTC (no draw); these are limited permits
// drawn via Montana's bonus-point system (points squared). Per permit (LPT;
// first 3 digits = hunting district): resident / non-resident 1st-choice
// applicants, successful, and success %.

export type MontanaPermit = {
  lpt: string;            // license/permit type code
  district: string;       // hunting district (first 3 digits of LPT)
  resApps: number | null;
  resSucc: number | null;
  resSuccessPct: number | null;  // resident 1st-choice draw success % (UNL → 100, no apps → null)
  nrApps: number | null;
  nrSucc: number | null;
  nrSuccessPct: number | null;
};

export const MONTANA_DRAW_YEAR = 2026;

export const MONTANA_DRAW: Record<string, MontanaPermit[]> = {
 "DEER": [
  {
   "lpt": "101-50",
   "district": "101",
   "resApps": 419,
   "resSucc": 13,
   "resSuccessPct": 3,
   "nrApps": 25,
   "nrSucc": 1,
   "nrSuccessPct": 4
  },
  {
   "lpt": "103-50",
   "district": "103",
   "resApps": 1000,
   "resSucc": 12,
   "resSuccessPct": 1,
   "nrApps": 32,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "130-50",
   "district": "130",
   "resApps": 296,
   "resSucc": 9,
   "resSuccessPct": 3,
   "nrApps": 13,
   "nrSucc": 1,
   "nrSuccessPct": 8
  },
  {
   "lpt": "202-50",
   "district": "202",
   "resApps": 880,
   "resSucc": 138,
   "resSuccessPct": 16,
   "nrApps": 58,
   "nrSucc": 11,
   "nrSuccessPct": 19
  },
  {
   "lpt": "210-50",
   "district": "210",
   "resApps": 969,
   "resSucc": 40,
   "resSuccessPct": 4,
   "nrApps": 27,
   "nrSucc": 2,
   "nrSuccessPct": 7
  },
  {
   "lpt": "240-50",
   "district": "240",
   "resApps": 110,
   "resSucc": 25,
   "resSuccessPct": 23,
   "nrApps": 5,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "250-50",
   "district": "250",
   "resApps": 802,
   "resSucc": 25,
   "resSuccessPct": 3,
   "nrApps": 28,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "261-50",
   "district": "261",
   "resApps": 954,
   "resSucc": 8,
   "resSuccessPct": 1,
   "nrApps": 51,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "262-51",
   "district": "262",
   "resApps": 308,
   "resSucc": 19,
   "resSuccessPct": 6,
   "nrApps": 11,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "262-52",
   "district": "262",
   "resApps": 61,
   "resSucc": 9,
   "resSuccessPct": 15,
   "nrApps": 2,
   "nrSucc": 1,
   "nrSuccessPct": 50
  },
  {
   "lpt": "270-50",
   "district": "270",
   "resApps": 10389,
   "resSucc": 36,
   "resSuccessPct": 0,
   "nrApps": 721,
   "nrSucc": 2,
   "nrSuccessPct": 0
  },
  {
   "lpt": "270-51",
   "district": "270",
   "resApps": 654,
   "resSucc": 14,
   "resSuccessPct": 2,
   "nrApps": 38,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "282-50",
   "district": "282",
   "resApps": 136,
   "resSucc": 6,
   "resSuccessPct": 4,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "282-51",
   "district": "282",
   "resApps": 509,
   "resSucc": 25,
   "resSuccessPct": 5,
   "nrApps": 10,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "291-50",
   "district": "291",
   "resApps": 947,
   "resSucc": 24,
   "resSuccessPct": 3,
   "nrApps": 59,
   "nrSucc": 1,
   "nrSuccessPct": 2
  },
  {
   "lpt": "291-51",
   "district": "291",
   "resApps": 132,
   "resSucc": 28,
   "resSuccessPct": 21,
   "nrApps": 2,
   "nrSucc": 1,
   "nrSuccessPct": 50
  },
  {
   "lpt": "300-50",
   "district": "300",
   "resApps": 1148,
   "resSucc": 25,
   "resSuccessPct": 2,
   "nrApps": 79,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "312-50",
   "district": "312",
   "resApps": 1023,
   "resSucc": 36,
   "resSuccessPct": 4,
   "nrApps": 21,
   "nrSucc": 1,
   "nrSuccessPct": 5
  },
  {
   "lpt": "319-50",
   "district": "319",
   "resApps": 658,
   "resSucc": 111,
   "resSuccessPct": 17,
   "nrApps": 74,
   "nrSucc": 12,
   "nrSuccessPct": 16
  },
  {
   "lpt": "380-50",
   "district": "380",
   "resApps": 1431,
   "resSucc": 652,
   "resSuccessPct": 46,
   "nrApps": 66,
   "nrSucc": 39,
   "nrSuccessPct": 59
  },
  {
   "lpt": "392-50",
   "district": "392",
   "resApps": 570,
   "resSucc": 466,
   "resSuccessPct": 82,
   "nrApps": 42,
   "nrSucc": 34,
   "nrSuccessPct": 81
  },
  {
   "lpt": "400-50",
   "district": "400",
   "resApps": 226,
   "resSucc": 100,
   "resSuccessPct": 44,
   "nrApps": 13,
   "nrSucc": 5,
   "nrSuccessPct": 38
  },
  {
   "lpt": "400-51",
   "district": "400",
   "resApps": 176,
   "resSucc": 28,
   "resSuccessPct": 16,
   "nrApps": 9,
   "nrSucc": 1,
   "nrSuccessPct": 11
  },
  {
   "lpt": "401-50",
   "district": "401",
   "resApps": 232,
   "resSucc": 121,
   "resSuccessPct": 52,
   "nrApps": 32,
   "nrSucc": 12,
   "nrSuccessPct": 38
  },
  {
   "lpt": "401-51",
   "district": "401",
   "resApps": 204,
   "resSucc": 41,
   "resSuccessPct": 20,
   "nrApps": 13,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "403-50",
   "district": "403",
   "resApps": 29,
   "resSucc": 25,
   "resSuccessPct": 86,
   "nrApps": 3,
   "nrSucc": 3,
   "nrSuccessPct": 100
  },
  {
   "lpt": "403-51",
   "district": "403",
   "resApps": 34,
   "resSucc": 9,
   "resSuccessPct": 26,
   "nrApps": 1,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "406-50",
   "district": "406",
   "resApps": 75,
   "resSucc": 42,
   "resSuccessPct": 56,
   "nrApps": 2,
   "nrSucc": 1,
   "nrSuccessPct": 50
  },
  {
   "lpt": "406-51",
   "district": "406",
   "resApps": 186,
   "resSucc": 21,
   "resSuccessPct": 11,
   "nrApps": 3,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "410-50",
   "district": "410",
   "resApps": 1039,
   "resSucc": 80,
   "resSuccessPct": 8,
   "nrApps": 134,
   "nrSucc": 5,
   "nrSuccessPct": 4
  },
  {
   "lpt": "417-50",
   "district": "417",
   "resApps": 453,
   "resSucc": 80,
   "resSuccessPct": 18,
   "nrApps": 76,
   "nrSucc": 5,
   "nrSuccessPct": 7
  },
  {
   "lpt": "426-50",
   "district": "426",
   "resApps": 305,
   "resSucc": 64,
   "resSuccessPct": 21,
   "nrApps": 46,
   "nrSucc": 4,
   "nrSuccessPct": 9
  },
  {
   "lpt": "441-50",
   "district": "441",
   "resApps": 911,
   "resSucc": 29,
   "resSuccessPct": 3,
   "nrApps": 16,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "447-50",
   "district": "447",
   "resApps": 86,
   "resSucc": 45,
   "resSuccessPct": 52,
   "nrApps": 14,
   "nrSucc": 5,
   "nrSuccessPct": 36
  },
  {
   "lpt": "447-51",
   "district": "447",
   "resApps": 20,
   "resSucc": 18,
   "resSuccessPct": 90,
   "nrApps": 4,
   "nrSucc": 2,
   "nrSuccessPct": 50
  },
  {
   "lpt": "455-60",
   "district": "455",
   "resApps": 1438,
   "resSucc": 15,
   "resSuccessPct": 1,
   "nrApps": 45,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "471-50",
   "district": "471",
   "resApps": 65,
   "resSucc": 65,
   "resSuccessPct": 100,
   "nrApps": 1,
   "nrSucc": 1,
   "nrSuccessPct": 100
  },
  {
   "lpt": "535-50",
   "district": "535",
   "resApps": 1125,
   "resSucc": 425,
   "resSuccessPct": 38,
   "nrApps": 113,
   "nrSucc": 46,
   "nrSuccessPct": 41
  },
  {
   "lpt": "652-50",
   "district": "652",
   "resApps": 884,
   "resSucc": 90,
   "resSuccessPct": 10,
   "nrApps": 179,
   "nrSucc": 6,
   "nrSuccessPct": 3
  }
 ],
 "ELK": [
  {
   "lpt": "101-50",
   "district": "101",
   "resApps": 282,
   "resSucc": 282,
   "resSuccessPct": 100,
   "nrApps": 14,
   "nrSucc": 14,
   "nrSuccessPct": 100
  },
  {
   "lpt": "217-10",
   "district": "217",
   "resApps": 649,
   "resSucc": 159,
   "resSuccessPct": 24,
   "nrApps": 40,
   "nrSucc": 11,
   "nrSuccessPct": 28
  },
  {
   "lpt": "217-11",
   "district": "217",
   "resApps": 55,
   "resSucc": 24,
   "resSuccessPct": 44,
   "nrApps": 2,
   "nrSucc": 1,
   "nrSuccessPct": 50
  },
  {
   "lpt": "250-45",
   "district": "250",
   "resApps": 1513,
   "resSucc": 43,
   "resSuccessPct": 3,
   "nrApps": 69,
   "nrSucc": 2,
   "nrSuccessPct": 3
  },
  {
   "lpt": "250-46",
   "district": "250",
   "resApps": 490,
   "resSucc": 42,
   "resSuccessPct": 9,
   "nrApps": 27,
   "nrSucc": 3,
   "nrSuccessPct": 11
  },
  {
   "lpt": "262-45",
   "district": "262",
   "resApps": 62,
   "resSucc": 18,
   "resSuccessPct": 29,
   "nrApps": 4,
   "nrSucc": 2,
   "nrSuccessPct": 50
  },
  {
   "lpt": "270-45",
   "district": "270",
   "resApps": 3305,
   "resSucc": 3305,
   "resSuccessPct": 100,
   "nrApps": 528,
   "nrSucc": 528,
   "nrSuccessPct": 100
  },
  {
   "lpt": "282-10",
   "district": "282",
   "resApps": 196,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "310-46",
   "district": "310",
   "resApps": 1216,
   "resSucc": 5,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "313-45",
   "district": "313",
   "resApps": 788,
   "resSucc": 43,
   "resSuccessPct": 5,
   "nrApps": 80,
   "nrSucc": 5,
   "nrSuccessPct": 6
  },
  {
   "lpt": "339-20",
   "district": "339",
   "resApps": 1172,
   "resSucc": 33,
   "resSuccessPct": 3,
   "nrApps": 38,
   "nrSucc": 1,
   "nrSuccessPct": 3
  },
  {
   "lpt": "380-20",
   "district": "380",
   "resApps": 11328,
   "resSucc": 84,
   "resSuccessPct": 1,
   "nrApps": 615,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "401-20",
   "district": "401",
   "resApps": 436,
   "resSucc": 41,
   "resSuccessPct": 9,
   "nrApps": 26,
   "nrSucc": 1,
   "nrSuccessPct": 4
  },
  {
   "lpt": "410-20",
   "district": "410",
   "resApps": 4108,
   "resSucc": 61,
   "resSuccessPct": 1,
   "nrApps": 233,
   "nrSucc": 2,
   "nrSuccessPct": 1
  },
  {
   "lpt": "410-21",
   "district": "410",
   "resApps": 1196,
   "resSucc": 885,
   "resSuccessPct": 74,
   "nrApps": 341,
   "nrSucc": 98,
   "nrSuccessPct": 29
  },
  {
   "lpt": "411-20",
   "district": "411",
   "resApps": 3005,
   "resSucc": 273,
   "resSuccessPct": 9,
   "nrApps": 220,
   "nrSucc": 24,
   "nrSuccessPct": 11
  },
  {
   "lpt": "411-21",
   "district": "411",
   "resApps": 726,
   "resSucc": 726,
   "resSuccessPct": 100,
   "nrApps": 182,
   "nrSucc": 182,
   "nrSuccessPct": 100
  },
  {
   "lpt": "412-20",
   "district": "412",
   "resApps": 489,
   "resSucc": 92,
   "resSuccessPct": 19,
   "nrApps": 51,
   "nrSucc": 10,
   "nrSuccessPct": 20
  },
  {
   "lpt": "417-20",
   "district": "417",
   "resApps": 919,
   "resSucc": 183,
   "resSuccessPct": 20,
   "nrApps": 140,
   "nrSucc": 19,
   "nrSuccessPct": 14
  },
  {
   "lpt": "417-21",
   "district": "417",
   "resApps": 350,
   "resSucc": 267,
   "resSuccessPct": 76,
   "nrApps": 121,
   "nrSucc": 28,
   "nrSuccessPct": 23
  },
  {
   "lpt": "420-20",
   "district": "420",
   "resApps": 517,
   "resSucc": 66,
   "resSuccessPct": 13,
   "nrApps": 41,
   "nrSucc": 7,
   "nrSuccessPct": 17
  },
  {
   "lpt": "425-20",
   "district": "425",
   "resApps": 1091,
   "resSucc": 4,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "426-20",
   "district": "426",
   "resApps": 396,
   "resSucc": 46,
   "resSuccessPct": 12,
   "nrApps": 51,
   "nrSucc": 5,
   "nrSuccessPct": 10
  },
  {
   "lpt": "441-20",
   "district": "441",
   "resApps": 514,
   "resSucc": 28,
   "resSuccessPct": 5,
   "nrApps": 12,
   "nrSucc": 1,
   "nrSuccessPct": 8
  },
  {
   "lpt": "445-20",
   "district": "445",
   "resApps": 710,
   "resSucc": 28,
   "resSuccessPct": 4,
   "nrApps": 28,
   "nrSucc": 1,
   "nrSuccessPct": 4
  },
  {
   "lpt": "447-20",
   "district": "447",
   "resApps": 1264,
   "resSucc": 81,
   "resSuccessPct": 6,
   "nrApps": 72,
   "nrSucc": 4,
   "nrSuccessPct": 6
  },
  {
   "lpt": "447-21",
   "district": "447",
   "resApps": 262,
   "resSucc": 262,
   "resSuccessPct": 100,
   "nrApps": 71,
   "nrSucc": 71,
   "nrSuccessPct": 100
  },
  {
   "lpt": "455-20",
   "district": "455",
   "resApps": 829,
   "resSucc": 50,
   "resSuccessPct": 6,
   "nrApps": 44,
   "nrSucc": 5,
   "nrSuccessPct": 11
  },
  {
   "lpt": "455-21",
   "district": "455",
   "resApps": 64,
   "resSucc": 64,
   "resSuccessPct": 100,
   "nrApps": 21,
   "nrSucc": 10,
   "nrSuccessPct": 48
  },
  {
   "lpt": "502-20",
   "district": "502",
   "resApps": 194,
   "resSucc": 4,
   "resSuccessPct": 2,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "555-20",
   "district": "555",
   "resApps": 425,
   "resSucc": 21,
   "resSuccessPct": 5,
   "nrApps": 25,
   "nrSucc": 2,
   "nrSuccessPct": 8
  },
  {
   "lpt": "590-20",
   "district": "590",
   "resApps": 1398,
   "resSucc": 300,
   "resSuccessPct": 21,
   "nrApps": 120,
   "nrSucc": 23,
   "nrSuccessPct": 19
  },
  {
   "lpt": "595-21",
   "district": "595",
   "resApps": 974,
   "resSucc": 974,
   "resSuccessPct": 100,
   "nrApps": 274,
   "nrSucc": 274,
   "nrSuccessPct": 100
  },
  {
   "lpt": "620-20",
   "district": "620",
   "resApps": 705,
   "resSucc": 55,
   "resSuccessPct": 8,
   "nrApps": 51,
   "nrSucc": 4,
   "nrSuccessPct": 8
  },
  {
   "lpt": "620-21",
   "district": "620",
   "resApps": 815,
   "resSucc": 814,
   "resSuccessPct": 100,
   "nrApps": 190,
   "nrSucc": 98,
   "nrSuccessPct": 52
  },
  {
   "lpt": "621-20",
   "district": "621",
   "resApps": 986,
   "resSucc": 45,
   "resSuccessPct": 5,
   "nrApps": 77,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "622-20",
   "district": "622",
   "resApps": 919,
   "resSucc": 55,
   "resSuccessPct": 6,
   "nrApps": 86,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "630-20",
   "district": "630",
   "resApps": 403,
   "resSucc": 21,
   "resSuccessPct": 5,
   "nrApps": 31,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "630-21",
   "district": "630",
   "resApps": 173,
   "resSucc": 89,
   "resSuccessPct": 51,
   "nrApps": 39,
   "nrSucc": 10,
   "nrSuccessPct": 26
  },
  {
   "lpt": "690-20",
   "district": "690",
   "resApps": 1568,
   "resSucc": 37,
   "resSuccessPct": 2,
   "nrApps": 178,
   "nrSucc": 5,
   "nrSuccessPct": 3
  },
  {
   "lpt": "690-21",
   "district": "690",
   "resApps": 721,
   "resSucc": 39,
   "resSuccessPct": 5,
   "nrApps": 119,
   "nrSucc": 3,
   "nrSuccessPct": 3
  },
  {
   "lpt": "700-20",
   "district": "700",
   "resApps": 2407,
   "resSucc": 194,
   "resSuccessPct": 8,
   "nrApps": 279,
   "nrSucc": 20,
   "nrSuccessPct": 7
  },
  {
   "lpt": "700-21",
   "district": "700",
   "resApps": 613,
   "resSucc": 612,
   "resSuccessPct": 100,
   "nrApps": 286,
   "nrSucc": 77,
   "nrSuccessPct": 27
  },
  {
   "lpt": "702-20",
   "district": "702",
   "resApps": 261,
   "resSucc": 119,
   "resSuccessPct": 46,
   "nrApps": 46,
   "nrSucc": 12,
   "nrSuccessPct": 26
  },
  {
   "lpt": "799-20",
   "district": "799",
   "resApps": 3553,
   "resSucc": 249,
   "resSuccessPct": 7,
   "nrApps": 523,
   "nrSucc": 27,
   "nrSuccessPct": 5
  },
  {
   "lpt": "799-21",
   "district": "799",
   "resApps": 1569,
   "resSucc": 875,
   "resSuccessPct": 56,
   "nrApps": 562,
   "nrSucc": 79,
   "nrSuccessPct": 14
  }
 ],
 "ANTELOPE": [
  {
   "lpt": "007-20",
   "district": "007",
   "resApps": 6624,
   "resSucc": 5777,
   "resSuccessPct": 87,
   "nrApps": 3285,
   "nrSucc": 616,
   "nrSuccessPct": 19
  },
  {
   "lpt": "007-21",
   "district": "007",
   "resApps": 4210,
   "resSucc": 3141,
   "resSuccessPct": 75,
   "nrApps": 1165,
   "nrSucc": 326,
   "nrSuccessPct": 28
  },
  {
   "lpt": "215-20",
   "district": "215",
   "resApps": 245,
   "resSucc": 4,
   "resSuccessPct": 2,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "291-20",
   "district": "291",
   "resApps": 71,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "300-20",
   "district": "300",
   "resApps": 706,
   "resSucc": 226,
   "resSuccessPct": 32,
   "nrApps": 143,
   "nrSucc": 23,
   "nrSuccessPct": 16
  },
  {
   "lpt": "301-20",
   "district": "301",
   "resApps": 78,
   "resSucc": 18,
   "resSuccessPct": 23,
   "nrApps": 20,
   "nrSucc": 1,
   "nrSuccessPct": 5
  },
  {
   "lpt": "310-20",
   "district": "310",
   "resApps": 773,
   "resSucc": 63,
   "resSuccessPct": 8,
   "nrApps": 86,
   "nrSucc": 6,
   "nrSuccessPct": 7
  },
  {
   "lpt": "311-20",
   "district": "311",
   "resApps": 235,
   "resSucc": 64,
   "resSuccessPct": 27,
   "nrApps": 17,
   "nrSucc": 2,
   "nrSuccessPct": 12
  },
  {
   "lpt": "313-20",
   "district": "313",
   "resApps": 107,
   "resSucc": 8,
   "resSuccessPct": 7,
   "nrApps": 7,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "317-20",
   "district": "317",
   "resApps": 185,
   "resSucc": 41,
   "resSuccessPct": 22,
   "nrApps": 21,
   "nrSucc": 3,
   "nrSuccessPct": 14
  },
  {
   "lpt": "318-20",
   "district": "318",
   "resApps": 423,
   "resSucc": 44,
   "resSuccessPct": 10,
   "nrApps": 23,
   "nrSucc": 2,
   "nrSuccessPct": 9
  },
  {
   "lpt": "319-20",
   "district": "319",
   "resApps": 224,
   "resSucc": 46,
   "resSuccessPct": 21,
   "nrApps": 7,
   "nrSucc": 1,
   "nrSuccessPct": 14
  },
  {
   "lpt": "320-20",
   "district": "320",
   "resApps": 360,
   "resSucc": 20,
   "resSuccessPct": 6,
   "nrApps": 67,
   "nrSucc": 2,
   "nrSuccessPct": 3
  },
  {
   "lpt": "322-20",
   "district": "322",
   "resApps": 3236,
   "resSucc": 259,
   "resSuccessPct": 8,
   "nrApps": 529,
   "nrSucc": 27,
   "nrSuccessPct": 5
  },
  {
   "lpt": "329-20",
   "district": "329",
   "resApps": 447,
   "resSucc": 92,
   "resSuccessPct": 21,
   "nrApps": 59,
   "nrSucc": 8,
   "nrSuccessPct": 14
  },
  {
   "lpt": "338-20",
   "district": "338",
   "resApps": 369,
   "resSucc": 81,
   "resSuccessPct": 22,
   "nrApps": 49,
   "nrSucc": 10,
   "nrSuccessPct": 20
  },
  {
   "lpt": "339-20",
   "district": "339",
   "resApps": 104,
   "resSucc": 67,
   "resSuccessPct": 64,
   "nrApps": 18,
   "nrSucc": 7,
   "nrSuccessPct": 39
  },
  {
   "lpt": "340-20",
   "district": "340",
   "resApps": 1158,
   "resSucc": 312,
   "resSuccessPct": 27,
   "nrApps": 130,
   "nrSucc": 30,
   "nrSuccessPct": 23
  },
  {
   "lpt": "350-20",
   "district": "350",
   "resApps": 334,
   "resSucc": 48,
   "resSuccessPct": 14,
   "nrApps": 24,
   "nrSucc": 5,
   "nrSuccessPct": 21
  },
  {
   "lpt": "360-20",
   "district": "360",
   "resApps": 703,
   "resSucc": 316,
   "resSuccessPct": 45,
   "nrApps": 114,
   "nrSucc": 32,
   "nrSuccessPct": 28
  },
  {
   "lpt": "370-20",
   "district": "370",
   "resApps": 191,
   "resSucc": 67,
   "resSuccessPct": 35,
   "nrApps": 14,
   "nrSucc": 7,
   "nrSuccessPct": 50
  },
  {
   "lpt": "371-20",
   "district": "371",
   "resApps": 375,
   "resSucc": 40,
   "resSuccessPct": 11,
   "nrApps": 8,
   "nrSucc": 2,
   "nrSuccessPct": 25
  },
  {
   "lpt": "380-20",
   "district": "380",
   "resApps": 237,
   "resSucc": 8,
   "resSuccessPct": 3,
   "nrApps": 6,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "381-20",
   "district": "381",
   "resApps": 90,
   "resSucc": 13,
   "resSuccessPct": 14,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "388-20",
   "district": "388",
   "resApps": 42,
   "resSucc": 15,
   "resSuccessPct": 36,
   "nrApps": 2,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "390-20",
   "district": "390",
   "resApps": 325,
   "resSucc": 20,
   "resSuccessPct": 6,
   "nrApps": 28,
   "nrSucc": 1,
   "nrSuccessPct": 4
  },
  {
   "lpt": "401-20",
   "district": "401",
   "resApps": 1148,
   "resSucc": 161,
   "resSuccessPct": 14,
   "nrApps": 88,
   "nrSucc": 9,
   "nrSuccessPct": 10
  },
  {
   "lpt": "404-20",
   "district": "404",
   "resApps": 2101,
   "resSucc": 148,
   "resSuccessPct": 7,
   "nrApps": 232,
   "nrSucc": 16,
   "nrSuccessPct": 7
  },
  {
   "lpt": "420-20",
   "district": "420",
   "resApps": 411,
   "resSucc": 59,
   "resSuccessPct": 14,
   "nrApps": 40,
   "nrSucc": 3,
   "nrSuccessPct": 8
  },
  {
   "lpt": "430-20",
   "district": "430",
   "resApps": 680,
   "resSucc": 194,
   "resSuccessPct": 29,
   "nrApps": 79,
   "nrSucc": 14,
   "nrSuccessPct": 18
  },
  {
   "lpt": "440-20",
   "district": "440",
   "resApps": 476,
   "resSucc": 109,
   "resSuccessPct": 23,
   "nrApps": 27,
   "nrSucc": 6,
   "nrSuccessPct": 22
  },
  {
   "lpt": "441-20",
   "district": "441",
   "resApps": 83,
   "resSucc": 17,
   "resSuccessPct": 20,
   "nrApps": 6,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "444-20",
   "district": "444",
   "resApps": 523,
   "resSucc": 79,
   "resSuccessPct": 15,
   "nrApps": 29,
   "nrSucc": 6,
   "nrSuccessPct": 21
  },
  {
   "lpt": "450-20",
   "district": "450",
   "resApps": 279,
   "resSucc": 66,
   "resSuccessPct": 24,
   "nrApps": 16,
   "nrSucc": 2,
   "nrSuccessPct": 13
  },
  {
   "lpt": "455-20",
   "district": "455",
   "resApps": 60,
   "resSucc": 2,
   "resSuccessPct": 3,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "471-20",
   "district": "471",
   "resApps": 1339,
   "resSucc": 283,
   "resSuccessPct": 21,
   "nrApps": 120,
   "nrSucc": 25,
   "nrSuccessPct": 21
  },
  {
   "lpt": "480-20",
   "district": "480",
   "resApps": 578,
   "resSucc": 116,
   "resSuccessPct": 20,
   "nrApps": 108,
   "nrSucc": 11,
   "nrSuccessPct": 10
  },
  {
   "lpt": "481-20",
   "district": "481",
   "resApps": 490,
   "resSucc": 119,
   "resSuccessPct": 24,
   "nrApps": 49,
   "nrSucc": 8,
   "nrSuccessPct": 16
  },
  {
   "lpt": "490-20",
   "district": "490",
   "resApps": 860,
   "resSucc": 130,
   "resSuccessPct": 15,
   "nrApps": 119,
   "nrSucc": 15,
   "nrSuccessPct": 13
  },
  {
   "lpt": "506-20",
   "district": "506",
   "resApps": 233,
   "resSucc": 178,
   "resSuccessPct": 76,
   "nrApps": 65,
   "nrSucc": 18,
   "nrSuccessPct": 28
  },
  {
   "lpt": "516-20",
   "district": "516",
   "resApps": 1370,
   "resSucc": 625,
   "resSuccessPct": 46,
   "nrApps": 221,
   "nrSucc": 65,
   "nrSuccessPct": 29
  },
  {
   "lpt": "526-20",
   "district": "526",
   "resApps": 272,
   "resSucc": 221,
   "resSuccessPct": 81,
   "nrApps": 38,
   "nrSucc": 23,
   "nrSuccessPct": 61
  },
  {
   "lpt": "536-20",
   "district": "536",
   "resApps": 631,
   "resSucc": 260,
   "resSuccessPct": 41,
   "nrApps": 95,
   "nrSucc": 21,
   "nrSuccessPct": 22
  },
  {
   "lpt": "546-20",
   "district": "546",
   "resApps": 453,
   "resSucc": 359,
   "resSuccessPct": 79,
   "nrApps": 85,
   "nrSucc": 39,
   "nrSuccessPct": 46
  },
  {
   "lpt": "556-20",
   "district": "556",
   "resApps": 455,
   "resSucc": 104,
   "resSuccessPct": 23,
   "nrApps": 64,
   "nrSucc": 12,
   "nrSuccessPct": 19
  },
  {
   "lpt": "576-20",
   "district": "576",
   "resApps": 2312,
   "resSucc": 971,
   "resSuccessPct": 42,
   "nrApps": 245,
   "nrSucc": 103,
   "nrSuccessPct": 42
  },
  {
   "lpt": "586-20",
   "district": "586",
   "resApps": 466,
   "resSucc": 404,
   "resSuccessPct": 87,
   "nrApps": 107,
   "nrSucc": 45,
   "nrSuccessPct": 42
  },
  {
   "lpt": "596-20",
   "district": "596",
   "resApps": 389,
   "resSucc": 267,
   "resSuccessPct": 69,
   "nrApps": 59,
   "nrSucc": 24,
   "nrSuccessPct": 41
  },
  {
   "lpt": "600-20",
   "district": "600",
   "resApps": 1013,
   "resSucc": 341,
   "resSuccessPct": 34,
   "nrApps": 122,
   "nrSucc": 38,
   "nrSuccessPct": 31
  },
  {
   "lpt": "620-20",
   "district": "620",
   "resApps": 1628,
   "resSucc": 516,
   "resSuccessPct": 32,
   "nrApps": 318,
   "nrSucc": 55,
   "nrSuccessPct": 17
  },
  {
   "lpt": "630-20",
   "district": "630",
   "resApps": 784,
   "resSucc": 256,
   "resSuccessPct": 33,
   "nrApps": 258,
   "nrSucc": 29,
   "nrSuccessPct": 11
  },
  {
   "lpt": "640-20",
   "district": "640",
   "resApps": 372,
   "resSucc": 94,
   "resSuccessPct": 25,
   "nrApps": 90,
   "nrSucc": 12,
   "nrSuccessPct": 13
  },
  {
   "lpt": "650-20",
   "district": "650",
   "resApps": 1083,
   "resSucc": 612,
   "resSuccessPct": 57,
   "nrApps": 315,
   "nrSucc": 70,
   "nrSuccessPct": 22
  },
  {
   "lpt": "670-20",
   "district": "670",
   "resApps": 984,
   "resSucc": 344,
   "resSuccessPct": 35,
   "nrApps": 247,
   "nrSucc": 35,
   "nrSuccessPct": 14
  },
  {
   "lpt": "690-20",
   "district": "690",
   "resApps": 1359,
   "resSucc": 414,
   "resSuccessPct": 30,
   "nrApps": 207,
   "nrSucc": 42,
   "nrSuccessPct": 20
  }
 ],
 "MOOSE": [
  {
   "lpt": "100-50",
   "district": "100",
   "resApps": 823,
   "resSucc": 11,
   "resSuccessPct": 1,
   "nrApps": 265,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "101-50",
   "district": "101",
   "resApps": 387,
   "resSucc": 6,
   "resSuccessPct": 2,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "102-50",
   "district": "102",
   "resApps": 368,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "103-50",
   "district": "103",
   "resApps": 310,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "104-50",
   "district": "104",
   "resApps": 217,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "105-50",
   "district": "105",
   "resApps": 470,
   "resSucc": 11,
   "resSuccessPct": 2,
   "nrApps": 128,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "106-50",
   "district": "106",
   "resApps": 841,
   "resSucc": 11,
   "resSuccessPct": 1,
   "nrApps": 105,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "110-50",
   "district": "110",
   "resApps": 611,
   "resSucc": 9,
   "resSuccessPct": 1,
   "nrApps": 96,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "111-50",
   "district": "111",
   "resApps": 851,
   "resSucc": 7,
   "resSuccessPct": 1,
   "nrApps": 90,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "112-50",
   "district": "112",
   "resApps": 382,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 54,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "121-50",
   "district": "121",
   "resApps": 282,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 78,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "122-50",
   "district": "122",
   "resApps": 662,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 565,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "125-50",
   "district": "125",
   "resApps": 242,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 77,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "126-50",
   "district": "126",
   "resApps": 72,
   "resSucc": 2,
   "resSuccessPct": 3,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "140-50",
   "district": "140",
   "resApps": 228,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "141-50",
   "district": "141",
   "resApps": 145,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "150-50",
   "district": "150",
   "resApps": 87,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "210-50",
   "district": "210",
   "resApps": 789,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "211-50",
   "district": "211",
   "resApps": 281,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "213-50",
   "district": "213",
   "resApps": 516,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "214-50",
   "district": "214",
   "resApps": 125,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "215-50",
   "district": "215",
   "resApps": 257,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 30,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "220-50",
   "district": "220",
   "resApps": 347,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 56,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "230-50",
   "district": "230",
   "resApps": 686,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 96,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "240-50",
   "district": "240",
   "resApps": 218,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "261-50",
   "district": "261",
   "resApps": 226,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "270-50",
   "district": "270",
   "resApps": 636,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "280-50",
   "district": "280",
   "resApps": 92,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "285-50",
   "district": "285",
   "resApps": 158,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "292-50",
   "district": "292",
   "resApps": 164,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "293-50",
   "district": "293",
   "resApps": 720,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "300-00",
   "district": "300",
   "resApps": 54,
   "resSucc": 2,
   "resSuccessPct": 4,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "300-50",
   "district": "300",
   "resApps": 920,
   "resSucc": 5,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "301-00",
   "district": "301",
   "resApps": 37,
   "resSucc": 1,
   "resSuccessPct": 3,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "301-50",
   "district": "301",
   "resApps": 366,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "302-00",
   "district": "302",
   "resApps": 31,
   "resSucc": 1,
   "resSuccessPct": 3,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "302-50",
   "district": "302",
   "resApps": 241,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "303-00",
   "district": "303",
   "resApps": 40,
   "resSucc": 1,
   "resSuccessPct": 3,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "303-50",
   "district": "303",
   "resApps": 603,
   "resSucc": 3,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "310-50",
   "district": "310",
   "resApps": 711,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "311-50",
   "district": "311",
   "resApps": 196,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "312-50",
   "district": "312",
   "resApps": 633,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "313-50",
   "district": "313",
   "resApps": 572,
   "resSucc": 6,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "314-50",
   "district": "314",
   "resApps": 288,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "319-50",
   "district": "319",
   "resApps": 207,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "320-00",
   "district": "320",
   "resApps": 55,
   "resSucc": 3,
   "resSuccessPct": 5,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "320-50",
   "district": "320",
   "resApps": 928,
   "resSucc": 4,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "322-50",
   "district": "322",
   "resApps": 283,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "323-00",
   "district": "323",
   "resApps": 116,
   "resSucc": 5,
   "resSuccessPct": 4,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "323-50",
   "district": "323",
   "resApps": 1012,
   "resSucc": 5,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "324-00",
   "district": "324",
   "resApps": 43,
   "resSucc": 3,
   "resSuccessPct": 7,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "324-50",
   "district": "324",
   "resApps": 611,
   "resSucc": 6,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "325-00",
   "district": "325",
   "resApps": 20,
   "resSucc": 1,
   "resSuccessPct": 5,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "325-50",
   "district": "325",
   "resApps": 475,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "326-00",
   "district": "326",
   "resApps": 35,
   "resSucc": 2,
   "resSuccessPct": 6,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "326-50",
   "district": "326",
   "resApps": 507,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "327-00",
   "district": "327",
   "resApps": 13,
   "resSucc": 1,
   "resSuccessPct": 8,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "327-50",
   "district": "327",
   "resApps": 255,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "329-50",
   "district": "329",
   "resApps": 200,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "330-00",
   "district": "330",
   "resApps": 150,
   "resSucc": 8,
   "resSuccessPct": 5,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "330-50",
   "district": "330",
   "resApps": 2518,
   "resSucc": 7,
   "resSuccessPct": 0,
   "nrApps": 614,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "332-00",
   "district": "332",
   "resApps": 132,
   "resSucc": 7,
   "resSuccessPct": 5,
   "nrApps": 14,
   "nrSucc": 1,
   "nrSuccessPct": 7
  },
  {
   "lpt": "332-50",
   "district": "332",
   "resApps": 1601,
   "resSucc": 7,
   "resSuccessPct": 0,
   "nrApps": 396,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "334-50",
   "district": "334",
   "resApps": 2160,
   "resSucc": 6,
   "resSuccessPct": 0,
   "nrApps": 578,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "335-50",
   "district": "335",
   "resApps": 257,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 18,
   "nrSucc": 1,
   "nrSuccessPct": 6
  },
  {
   "lpt": "340-00",
   "district": "340",
   "resApps": 58,
   "resSucc": 2,
   "resSuccessPct": 3,
   "nrApps": 11,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "340-50",
   "district": "340",
   "resApps": 770,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 70,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "341-50",
   "district": "341",
   "resApps": 276,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 85,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "343-50",
   "district": "343",
   "resApps": 339,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 42,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "350-50",
   "district": "350",
   "resApps": 167,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 21,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "360-50",
   "district": "360",
   "resApps": 274,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 80,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "361-51",
   "district": "361",
   "resApps": 279,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 67,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "380-00",
   "district": "380",
   "resApps": 95,
   "resSucc": 2,
   "resSuccessPct": 2,
   "nrApps": 5,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "380-50",
   "district": "380",
   "resApps": 1401,
   "resSucc": 5,
   "resSuccessPct": 0,
   "nrApps": 115,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "382-50",
   "district": "382",
   "resApps": 171,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "390-50",
   "district": "390",
   "resApps": 337,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "401-20",
   "district": "401",
   "resApps": 304,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "415-50",
   "district": "415",
   "resApps": 138,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "422-50",
   "district": "422",
   "resApps": 337,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 84,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "441-50",
   "district": "441",
   "resApps": 338,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "447-50",
   "district": "447",
   "resApps": 292,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "494-50",
   "district": "494",
   "resApps": 559,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "496-50",
   "district": "496",
   "resApps": 1054,
   "resSucc": 4,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "513-50",
   "district": "513",
   "resApps": 303,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 82,
   "nrSucc": 0,
   "nrSuccessPct": 0
  },
  {
   "lpt": "514-50",
   "district": "514",
   "resApps": 1483,
   "resSucc": 6,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "516-50",
   "district": "516",
   "resApps": 298,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "600-20",
   "district": "600",
   "resApps": 2017,
   "resSucc": 9,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "700-20",
   "district": "700",
   "resApps": 584,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  }
 ],
 "BIGHORNSHEEP": [
  {
   "lpt": "100-20",
   "district": "100",
   "resApps": 662,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "102-20",
   "district": "102",
   "resApps": 259,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "121-20",
   "district": "121",
   "resApps": 817,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "122-20",
   "district": "122",
   "resApps": 546,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "123-20",
   "district": "123",
   "resApps": 339,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "124-20",
   "district": "124",
   "resApps": 1934,
   "resSucc": 5,
   "resSuccessPct": 0,
   "nrApps": 1453,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "124-30",
   "district": "124",
   "resApps": 91,
   "resSucc": 2,
   "resSuccessPct": 2,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "203-20",
   "district": "203",
   "resApps": 1163,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 1285,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "210-20",
   "district": "210",
   "resApps": 560,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "214-60",
   "district": "214",
   "resApps": 968,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "250-20",
   "district": "250",
   "resApps": 206,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "261-20",
   "district": "261",
   "resApps": 423,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "270-20",
   "district": "270",
   "resApps": 2531,
   "resSucc": 9,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "270-30",
   "district": "270",
   "resApps": 107,
   "resSucc": 11,
   "resSuccessPct": 10,
   "nrApps": 66,
   "nrSucc": 1,
   "nrSuccessPct": 2
  },
  {
   "lpt": "300-60",
   "district": "300",
   "resApps": 101,
   "resSucc": 101,
   "resSuccessPct": 100,
   "nrApps": 27,
   "nrSucc": 27,
   "nrSuccessPct": 100
  },
  {
   "lpt": "301-20",
   "district": "301",
   "resApps": 932,
   "resSucc": 3,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "302-20",
   "district": "302",
   "resApps": 799,
   "resSucc": 3,
   "resSuccessPct": 0,
   "nrApps": 497,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "303-60",
   "district": "303",
   "resApps": 128,
   "resSucc": 128,
   "resSuccessPct": 100,
   "nrApps": 38,
   "nrSucc": 38,
   "nrSuccessPct": 100
  },
  {
   "lpt": "304-20",
   "district": "304",
   "resApps": 296,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "305-10",
   "district": "305",
   "resApps": 187,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "330-10",
   "district": "330",
   "resApps": 330,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "340-20",
   "district": "340",
   "resApps": 1137,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "380-10",
   "district": "380",
   "resApps": 993,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "381-10",
   "district": "381",
   "resApps": 285,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "421-20",
   "district": "421",
   "resApps": 220,
   "resSucc": 0,
   "resSuccessPct": 0,
   "nrApps": 639,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "422-20",
   "district": "422",
   "resApps": 989,
   "resSucc": 4,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "423-20",
   "district": "423",
   "resApps": 364,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "424-20",
   "district": "424",
   "resApps": 749,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "441-20",
   "district": "441",
   "resApps": 418,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "455-20",
   "district": "455",
   "resApps": 861,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "482-20",
   "district": "482",
   "resApps": 5104,
   "resSucc": 5,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "482-30",
   "district": "482",
   "resApps": 146,
   "resSucc": 4,
   "resSuccessPct": 3,
   "nrApps": 30,
   "nrSucc": 1,
   "nrSuccessPct": 3
  },
  {
   "lpt": "500-60",
   "district": "500",
   "resApps": 99,
   "resSucc": 99,
   "resSuccessPct": 100,
   "nrApps": 37,
   "nrSucc": 37,
   "nrSuccessPct": 100
  },
  {
   "lpt": "501-60",
   "district": "501",
   "resApps": 132,
   "resSucc": 132,
   "resSuccessPct": 100,
   "nrApps": 55,
   "nrSucc": 55,
   "nrSuccessPct": 100
  },
  {
   "lpt": "502-60",
   "district": "502",
   "resApps": 104,
   "resSucc": 104,
   "resSuccessPct": 100,
   "nrApps": 19,
   "nrSucc": 19,
   "nrSuccessPct": 100
  },
  {
   "lpt": "503-20",
   "district": "503",
   "resApps": 766,
   "resSucc": 3,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "620-20",
   "district": "620",
   "resApps": 1152,
   "resSucc": 3,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "680-20",
   "district": "680",
   "resApps": 6338,
   "resSucc": 9,
   "resSuccessPct": 0,
   "nrApps": 3559,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "680-30",
   "district": "680",
   "resApps": 117,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "680-31",
   "district": "680",
   "resApps": 70,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  }
 ],
 "MTNGOAT": [
  {
   "lpt": "100-20",
   "district": "100",
   "resApps": 1310,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "101-20",
   "district": "101",
   "resApps": 316,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "133-20",
   "district": "133",
   "resApps": 319,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "140-20",
   "district": "140",
   "resApps": 762,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "142-20",
   "district": "142",
   "resApps": 131,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "150-20",
   "district": "150",
   "resApps": 189,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "240-20",
   "district": "240",
   "resApps": 1299,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "313-20",
   "district": "313",
   "resApps": 3351,
   "resSucc": 14,
   "resSuccessPct": 0,
   "nrApps": 626,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "314-20",
   "district": "314",
   "resApps": 1875,
   "resSucc": 27,
   "resSuccessPct": 1,
   "nrApps": 634,
   "nrSucc": 3,
   "nrSuccessPct": 0
  },
  {
   "lpt": "316-20",
   "district": "316",
   "resApps": 535,
   "resSucc": 11,
   "resSuccessPct": 2,
   "nrApps": 180,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "320-20",
   "district": "320",
   "resApps": 1424,
   "resSucc": 4,
   "resSuccessPct": 0,
   "nrApps": 262,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "323-20",
   "district": "323",
   "resApps": 1938,
   "resSucc": 35,
   "resSuccessPct": 2,
   "nrApps": 536,
   "nrSucc": 3,
   "nrSuccessPct": 1
  },
  {
   "lpt": "324-20",
   "district": "324",
   "resApps": 373,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 142,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "325-20",
   "district": "325",
   "resApps": 442,
   "resSucc": 6,
   "resSuccessPct": 1,
   "nrApps": 97,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "326-20",
   "district": "326",
   "resApps": 346,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 81,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "329-20",
   "district": "329",
   "resApps": 606,
   "resSucc": 14,
   "resSuccessPct": 2,
   "nrApps": 177,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "330-20",
   "district": "330",
   "resApps": 181,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 140,
   "nrSucc": 1,
   "nrSuccessPct": 1
  },
  {
   "lpt": "331-20",
   "district": "331",
   "resApps": 811,
   "resSucc": 3,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "350-20",
   "district": "350",
   "resApps": 1278,
   "resSucc": 2,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "361-20",
   "district": "361",
   "resApps": 334,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "362-20",
   "district": "362",
   "resApps": 353,
   "resSucc": 6,
   "resSuccessPct": 2,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "393-20",
   "district": "393",
   "resApps": 2329,
   "resSucc": 4,
   "resSuccessPct": 0,
   "nrApps": 880,
   "nrSucc": 1,
   "nrSuccessPct": 0
  },
  {
   "lpt": "415-20",
   "district": "415",
   "resApps": 230,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "442-20",
   "district": "442",
   "resApps": 466,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "447-20",
   "district": "447",
   "resApps": 1357,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "453-20",
   "district": "453",
   "resApps": 460,
   "resSucc": 1,
   "resSuccessPct": 0,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "514-20",
   "district": "514",
   "resApps": 279,
   "resSucc": 2,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "517-20",
   "district": "517",
   "resApps": 757,
   "resSucc": 4,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "518-20",
   "district": "518",
   "resApps": 305,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "519-20",
   "district": "519",
   "resApps": 124,
   "resSucc": 1,
   "resSuccessPct": 1,
   "nrApps": 0,
   "nrSucc": 0,
   "nrSuccessPct": null
  },
  {
   "lpt": "521-20",
   "district": "521",
   "resApps": 215,
   "resSucc": 3,
   "resSuccessPct": 1,
   "nrApps": 116,
   "nrSucc": 1,
   "nrSuccessPct": 1
  }
 ]
};

export function montanaHuntsForUnit(speciesKey: string, district: string): MontanaPermit[] {
  const d = String(parseInt(district, 10));
  return (MONTANA_DRAW[speciesKey] || []).filter((p) => String(parseInt(p.district, 10)) === d);
}

// Scout dataset: aggregated per district (success ranges) to stay compact.
export function buildMontanaScoutDataset(speciesKey: string): Array<Record<string, unknown>> {
  const byDist: Record<string, MontanaPermit[]> = {};
  for (const p of MONTANA_DRAW[speciesKey] || []) {
    (byDist[p.district] = byDist[p.district] || []).push(p);
  }
  return Object.entries(byDist).map(([district, permits]) => {
    const res = permits.map((p) => p.resSuccessPct).filter((v): v is number => v != null);
    const nr = permits.map((p) => p.nrSuccessPct).filter((v): v is number => v != null);
    const range = (a: number[]) => (a.length ? `${Math.min(...a)}-${Math.max(...a)}%` : 'n/a');
    return {
      unit: district,
      permits: permits.slice(0, 6).map((p) => p.lpt),
      permitCount: permits.length,
      resDrawSuccess: range(res),
      nonResDrawSuccess: range(nr),
      bestResSuccess: res.length ? Math.max(...res) : null,
      bestNonResSuccess: nr.length ? Math.max(...nr) : null,
    };
  });
}
