import type { Harvest, SpeciesKey, StateCode, Weapon } from '../schema';
import type { HarvestFile, HarvestRow } from './format';
import { normalizeUnit } from '../unitGuard';
import azHarvest from './az.json';
import coHarvest from './co.json';
import idHarvest from './id.json';
import mtHarvest from './mt.json';
import nmHarvest from './nm.json';
import ndHarvest from './nd.json';
import utHarvest from './ut.json';
import wyHarvest from './wy.json';

// Generated by scripts/harvest/build<ST>Harvest.mjs. Add a state here when its
// file lands.
const HARVEST: Partial<Record<StateCode, HarvestFile>> = {
  AZ: azHarvest as HarvestFile,
  CO: coHarvest as HarvestFile,
  ID: idHarvest as HarvestFile,
  MT: mtHarvest as HarvestFile,
  NM: nmHarvest as HarvestFile,
  ND: ndHarvest as HarvestFile,
  UT: utHarvest as HarvestFile,
  WY: wyHarvest as HarvestFile,
};

// Whether a hunt with no exact hunt-code row may use its unit's rows.
//   ID: no — unit rows are GENERAL seasons, which say nothing about a
//       controlled hunt in that unit.
//   MT: yes — FWP only reports district totals (general + permits); labelled
//       scope "unit" so prompts say it's district-wide, not the permit.
//   UT: yes — rows are per DWR hunt, but the app keys Utah by unit name.
const UNIT_FALLBACK: Partial<Record<StateCode, boolean>> = {
  ID: false,
  MT: true,
  UT: true,
  //   WY: no — exact "<area>-<type>" codes cover ~98%; area totals mix every
  //       license type, so they'd misstate a specific tag.
  WY: false,
  //   CO: no — every row is a CPW hunt code; another code in the same GMU
  //       (e.g. a cow hunt) says nothing about the hunter's own license.
  CO: false,
  //   AZ: no — every row is an AZGFD hunt number.
  AZ: false,
  //   NM: no — every row is an NMDGF hunt code.
  NM: false,
  //   ND: yes — elk/moose harvest is reported per unit (any + antlerless
  //       combined), labelled unit-wide; deer/pronghorn are statewide only.
  ND: true,
};

export function getHarvestFile(state: StateCode): HarvestFile | null {
  return HARVEST[state] ?? null;
}

// Season for a species (MT reports elk/antelope a year behind deer).
export function harvestYear(state: StateCode, species: SpeciesKey): number | null {
  const file = HARVEST[state];
  return file ? file.speciesYear?.[species] ?? file.year : null;
}

function rowsFor(state: StateCode, species: SpeciesKey): HarvestRow[] {
  return HARVEST[state]?.species[species] ?? [];
}

const toHarvest = (row: HarvestRow, year: number, scope: Harvest['scope']): Harvest => ({
  successPct: row.successPct,
  year,
  hunters: row.hunters,
  harvest: row.harvest,
  scope,
});

// Harvest for one hunt: exact hunt code first, then (where the state allows it)
// the unit's row for the same weapon.
export function harvestForHunt(
  state: StateCode,
  species: SpeciesKey,
  huntCode: string,
  unit: string,
  weapon?: Weapon,
): Harvest | null {
  const file = HARVEST[state];
  if (!file) return null;
  const rows = rowsFor(state, species);

  const byCode = rows.filter((r) => r.huntCode === huntCode);
  if (byCode.length) {
    // A hunt code can be reported once per take method; prefer the hunt's own weapon.
    const best = byCode.find((r) => weapon && r.weapon === weapon) ?? byCode[0];
    return toHarvest(best, harvestYear(state, species)!, 'hunt');
  }

  if (!UNIT_FALLBACK[state]) return null;
  const u = normalizeUnit(unit);
  const inUnit = rows.filter((r) => normalizeUnit(r.unit) === u);
  const best =
    inUnit.find((r) => weapon && r.weapon === weapon) ??
    inUnit.find((r) => !r.weapon || r.weapon === 'any');
  return best ? toHarvest(best, harvestYear(state, species)!, 'unit') : null;
}

// Every harvest row reported in a unit (controlled and general), for BRIEF.
// Some states pass a hunt key as the "unit" (WY "7-1"): if that matches a hunt
// code, return that hunt's rows first, then the rest of its area.
export function harvestRowsForUnit(state: StateCode, species: SpeciesKey, unit: string): HarvestRow[] {
  const rows = rowsFor(state, species);
  const exact = rows.filter((r) => r.huntCode === unit);
  const area = exact.length ? exact[0].unit : unit;
  const u = normalizeUnit(area);
  const inArea = rows.filter((r) => normalizeUnit(r.unit) === u && !exact.includes(r));
  return [...exact, ...inArea];
}

const pctRange = (a: number[]) =>
  Math.min(...a) === Math.max(...a) ? `${a[0]}%` : `${Math.min(...a)}-${Math.max(...a)}%`;

// Adds hunterSuccess to the entries of an existing SCOUT dataset. Entries are
// matched by hunt number/code first (ID "huntNumber", WY "unit" keys like
// "141-1"), then by unit when the state allows it.
export function enrichScoutDataset<T extends Record<string, unknown>>(
  state: StateCode,
  species: SpeciesKey,
  dataset: T[],
): Array<T & { hunterSuccess?: string; hunterSuccessYear?: number; hunterSuccessScope?: 'hunt' | 'unit' }> {
  const file = HARVEST[state];
  if (!file) return dataset;
  const rows = rowsFor(state, species);
  if (!rows.length) return dataset;

  return dataset.map((entry) => {
    // CO/MT SCOUT entries are per unit and list their hunt codes / permits.
    const listed = [entry.huntCodes, entry.permits].flatMap((v) => (Array.isArray(v) ? v : []));
    const codes = [entry.huntNumber, entry.huntCode, entry.unit, ...listed].filter((v) => v != null).map(String);
    const byCode = rows.filter((r) => r.huntCode && codes.includes(r.huntCode));
    let hits = byCode;
    if (!hits.length && UNIT_FALLBACK[state] && entry.unit != null) {
      const u = normalizeUnit(entry.unit);
      hits = rows.filter((r) => normalizeUnit(r.unit) === u);
    }
    if (!hits.length) return entry;
    return {
      ...entry,
      hunterSuccess: pctRange(hits.map((r) => r.successPct)),
      hunterSuccessYear: harvestYear(state, species)!,
      hunterSuccessScope: byCode.length ? 'hunt' : 'unit',
    };
  });
}

// Prompt instruction that goes with enrichScoutDataset.
export function harvestPromptNote(dataset: Array<Record<string, unknown>>): string {
  if (!dataset.some((e) => e.hunterSuccess)) return '';
  return `
HUNTER SUCCESS DATA: entries with "hunterSuccess" carry the state agency's reported share of hunters who harvested an animal (season "hunterSuccessYear"). Use it in whyItFits and tradeoffs, and weigh it alongside draw odds and trophy quality. A range means several seasons/weapons in that unit. hunterSuccessScope "hunt" = this exact hunt; "unit" = all hunters in the unit/district (general and limited combined), so say "unit-wide" when citing it. Entries without hunterSuccess have no published figure — do NOT estimate one.`;
}

// BRIEF block: every harvest row for the unit, labelled.
export function buildHarvestBlock(state: StateCode, species: SpeciesKey, speciesLabel: string, unit: string): string {
  const file = HARVEST[state];
  if (!file) return '';
  const rows = harvestRowsForUnit(state, species, unit);
  if (!rows.length) return '';
  const lines = rows.slice(0, 15).map((r) => {
    const counts = r.hunters != null && r.harvest != null ? ` (${r.harvest} harvested by ${r.hunters} hunters)` : '';
    const days = r.daysPerHarvest != null ? `, ${r.daysPerHarvest} hunter-days per animal` : '';
    return `- ${r.label ?? r.huntCode ?? 'All hunts'}: ${r.successPct}% hunter success${counts}${days}.`;
  }).join('\n');
  return `
          ### HARVEST SUCCESS (${harvestYear(state, species)}) — Unit ${unit} ${speciesLabel} ###
          Source: ${file.source.name}.${file.notes ? ` Notes: ${file.notes}` : ''}
          Use these exact figures for success rates; do not invent others. State the hunter success for the hunter's hunt in the DRAW ODDS section, next to the draw odds:
          ${lines}
          ###########################################
        `;
}
