// Ingests Montana limited-permit draw statistics from MT FWP's "Permit Drawing
// Statistics" reports into app/api/strategy/montanaDraw.ts.
//
// MT general deer/elk licenses are general/OTC (no draw); these are the LIMITED
// permits drawn via Montana's bonus-point system (points are squared). Per
// permit (LPT — first 3 digits = hunting district) we extract resident and
// non-resident 1st-choice applicants + successful → draw-success %.
//
// Source: myfwp.mt.gov drawing-statistics repository (a small 1-page-per-species
// PDF, parsed cleanly with `pdftotext -table`). Requires pdftotext on PATH.
// Run: node scripts/buildMontanaDraw.mjs
import { writeFileSync, readFileSync, existsSync, statSync } from 'node:fs';
import { execSync } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';

const UA = { 'User-Agent': 'Mozilla/5.0 (huntengine-app ingestion)' };
const BASE = 'https://myfwp.mt.gov';

// app speciesKey → MT repositoryObjectId
const SPECIES = {
  DEER: 28566,        // White-tailed/Mule Deer
  ELK: 28562,
  ANTELOPE: 28561,
  MOOSE: 28564,
  BIGHORNSHEEP: 28565,
  MTNGOAT: 28563,
};

async function text(url, opts) {
  const r = await fetch(url, { headers: UA, ...opts });
  if (!r.ok) throw new Error(`${url} → ${r.status}`);
  return r.text();
}

// repositoryList → latest "Permit Drawing Statistics" report file id + year.
async function resolveReport(objectId) {
  const html = await text(`${BASE}/fwpPub/repositoryList_input.action?repositoryObjectId=${objectId}`);
  const links = [...html.matchAll(/<a[^>]+href="([^"]*getRepositoryFile[^"]+)"[^>]*>([\s\S]*?)<\/a>/gi)]
    .map((m) => ({ href: m[1], label: m[2].replace(/<[^>]+>/g, '').replace(/&[a-z]+;/g, ' ').trim() }));
  // The main per-species report is "<Year> <Species> [Permit] Drawing Statistics
  // Report". Exclude the bonus-point/detailed breakdowns and sub-license variants
  // (B licenses, 900-20, archery-only, NR combination).
  const permit = links
    .filter((l) => /Drawing Statistics Report/i.test(l.label))
    .filter((l) => !/Bonus|Detailed|A9|B12|Combination|Archery|\d{3}-\d{2}|\b[AB] Drawing/i.test(l.label))
    .map((l) => ({ ...l, year: +(l.label.match(/\d{4}/) || [0])[0] }))
    // latest year; tie-break to the shortest label (the un-qualified main report)
    .sort((a, b) => b.year - a.year || a.label.length - b.label.length);
  if (!permit.length) throw new Error('no drawing report');
  return permit[0];
}

// Column layout (numeric/UNL tokens after the LPT): regular resident 1st-choice
// applicants=idx8 / successful=idx11; non-resident applicants=idx15 / succ=idx18.
function parseReport(txt) {
  const out = [];
  for (const line of txt.split('\n')) {
    const m = line.match(/^(\d{3}-\d{2})/);
    if (!m) continue;
    const lpt = m[1];
    const tok = line.split(/\s+/).filter((t) => /^(\d+|UNL)$/.test(t));
    if (tok.length < 19) continue;
    const val = (i) => (tok[i] === 'UNL' ? 'UNL' : parseInt(tok[i], 10));
    const rApps = val(8), rSucc = val(11), nApps = val(15), nSucc = val(18);
    const pct = (a, s) => (a === 'UNL' || s === 'UNL' ? 100 : a > 0 ? Math.round((100 * s) / a) : null);
    const resPct = pct(rApps, rSucc), nrPct = pct(nApps, nSucc);
    if (resPct == null && nrPct == null) continue;
    out.push({
      lpt,
      district: lpt.slice(0, 3),
      resApps: rApps === 'UNL' ? null : rApps,
      resSucc: rSucc === 'UNL' ? null : rSucc,
      resSuccessPct: resPct,
      nrApps: nApps === 'UNL' ? null : nApps,
      nrSucc: nSucc === 'UNL' ? null : nSucc,
      nrSuccessPct: nrPct,
    });
  }
  return out;
}

let dataYear = null;
const out = {};
for (const [key, objectId] of Object.entries(SPECIES)) {
  try {
    const { href, year } = await resolveReport(objectId);
    if (year) dataYear = Math.max(dataYear || 0, year);
    const tmpPdf = path.join(os.tmpdir(), `mt_${key}.pdf`);
    let buf;
    if (existsSync(tmpPdf) && statSync(tmpPdf).size > 1000) {
      buf = readFileSync(tmpPdf);
    } else {
      buf = Buffer.from(await (await fetch(href, { headers: UA })).arrayBuffer());
      writeFileSync(tmpPdf, buf);
    }
    const tmpTxt = tmpPdf.replace(/\.pdf$/, '.txt');
    execSync(`pdftotext -q -table "${tmpPdf}" "${tmpTxt}"`, { stdio: 'ignore', maxBuffer: 1 << 28 });
    const permits = parseReport(readFileSync(tmpTxt, 'utf8'));
    out[key] = permits;
    console.log(`${key}: ${permits.length} permits (${[...new Set(permits.map((p) => p.district))].length} districts)`);
  } catch (e) {
    console.error(`${key} failed:`, e.message);
    out[key] = [];
  }
}

const body = `// AUTO-GENERATED by scripts/buildMontanaDraw.mjs — do not edit by hand.
// Montana limited-permit DRAW SUCCESS (${dataYear ?? ''}) from MT FWP reports.
// General deer/elk licenses are general/OTC (no draw); these are limited permits
// drawn via Montana's bonus-point system (points squared). Per permit (LPT;
// first 3 digits = hunting district): resident / non-resident 1st-choice
// applicants, successful, and success %.

export type MontanaPermit = {
  lpt: string;            // license/permit type code
  district: string;       // hunting district (first 3 digits of LPT)
  resApps: number | null;
  resSucc: number | null;
  resSuccessPct: number | null;  // resident 1st-choice draw success % (UNL → 100, no apps → null)
  nrApps: number | null;
  nrSucc: number | null;
  nrSuccessPct: number | null;
};

export const MONTANA_DRAW_YEAR = ${dataYear ?? 'null'};

export const MONTANA_DRAW: Record<string, MontanaPermit[]> = ${JSON.stringify(out, null, 1)};

export function montanaHuntsForUnit(speciesKey: string, district: string): MontanaPermit[] {
  const d = String(parseInt(district, 10));
  return (MONTANA_DRAW[speciesKey] || []).filter((p) => String(parseInt(p.district, 10)) === d);
}

// Scout dataset: aggregated per district (success ranges) to stay compact.
export function buildMontanaScoutDataset(speciesKey: string): Array<Record<string, unknown>> {
  const byDist: Record<string, MontanaPermit[]> = {};
  for (const p of MONTANA_DRAW[speciesKey] || []) {
    (byDist[p.district] = byDist[p.district] || []).push(p);
  }
  return Object.entries(byDist).map(([district, permits]) => {
    const res = permits.map((p) => p.resSuccessPct).filter((v): v is number => v != null);
    const nr = permits.map((p) => p.nrSuccessPct).filter((v): v is number => v != null);
    const range = (a: number[]) => (a.length ? \`\${Math.min(...a)}-\${Math.max(...a)}%\` : 'n/a');
    return {
      unit: district,
      permits: permits.slice(0, 6).map((p) => p.lpt),
      permitCount: permits.length,
      resDrawSuccess: range(res),
      nonResDrawSuccess: range(nr),
      bestResSuccess: res.length ? Math.max(...res) : null,
      bestNonResSuccess: nr.length ? Math.max(...nr) : null,
    };
  });
}
`;

writeFileSync(new URL('../app/api/strategy/montanaDraw.ts', import.meta.url), body);
const total = Object.values(out).reduce((n, a) => n + a.length, 0);
console.log(`Wrote ${total} MT permits → app/api/strategy/montanaDraw.ts`);
