// Ingests Idaho controlled-hunt drawing odds from IDFG's Hunt Planner JSON API
// (https://fishandgame.idaho.gov/ifwis/huntplanner/api/1.1/odds/) into
// app/api/strategy/idahoDraw.ts.
//
// Idaho's general deer/elk seasons are OTC/general-tag (no draw); these are the
// LIMITED-ENTRY controlled hunts — the part with real draw odds. Keyed by the
// app's species, each hunt records tags, first-choice applicants, and draw odds
// (overall + resident/non-resident).
//
// Run: node scripts/buildIdahoDraw.mjs
import { writeFileSync } from 'node:fs';

const API = 'https://fishandgame.idaho.gov/ifwis/huntplanner/api/1.1/odds/';
const YEAR = 2025;

// app speciesKey → IDFG biggame code
const SPECIES = {
  DEER: 1,
  ELK: 2,
  ANTELOPE: 3, // IDFG "Pronghorn"
  MOOSE: 6,
  BIGHORNSHEEP: 7, // IDFG "Rocky Mountain Sheep"
  MTNGOAT: 8,
};

async function fetchSpecies(code) {
  const url = `${API}?biggame=${code}&yr=${YEAR}&draw=1&limit=10000&offset=0`;
  const r = await fetch(url, { headers: { 'User-Agent': 'huntengine-app/1.0', 'X-Requested-With': 'XMLHttpRequest' } });
  if (!r.ok) throw new Error(`${code} → ${r.status}`);
  const j = await r.json();
  return (j.rows || []).map((row) => ({
    hunt: Number(row.CHunt),
    area: String(row.CHuntArea),
    tags: Number(row.PermitTotal) || 0,
    applicants: Number(row.ApplChoice1) || 0,
    resApplicants: Number(row.ResApp) || 0,
    nonResApplicants: Number(row.NonResApp) || 0,
    oddsPct: Number(row.PercChoice1) || 0,
    resOddsPct: Number(row.PercRes1) || 0,
    nonResOddsPct: Number(row.PercNonRes1) || 0,
  }));
}

const out = {};
for (const [key, code] of Object.entries(SPECIES)) {
  try {
    const hunts = await fetchSpecies(code);
    out[key] = hunts.sort((a, b) => a.hunt - b.hunt);
    console.log(`${key}: ${hunts.length} controlled hunts`);
  } catch (e) {
    console.error(`${key} failed:`, e.message);
    out[key] = [];
  }
}

const body = `// AUTO-GENERATED by scripts/buildIdahoDraw.mjs — do not edit by hand.
// Idaho controlled-hunt drawing odds (${YEAR}), from IDFG Hunt Planner API.
// General deer/elk seasons are OTC/general (no draw); these are limited-entry hunts.

export type IdahoHunt = {
  hunt: number;          // controlled hunt number
  area: string;          // hunt area (often a GMU, sometimes a sub-area like "11A")
  tags: number;          // permits available
  applicants: number;    // first-choice applicants
  resApplicants: number;
  nonResApplicants: number;
  oddsPct: number;       // first-choice draw odds %
  resOddsPct: number;
  nonResOddsPct: number;
};

export const IDAHO_DRAW_YEAR = ${YEAR};

export const IDAHO_DRAW: Record<string, IdahoHunt[]> = ${JSON.stringify(out, null, 1)};

// Controlled hunts whose area resolves to the given GMU (matches the area's
// leading number, so "11", "11A", "1-1" all map to their GMU).
export function idahoHuntsForUnit(speciesKey: string, gmu: string): IdahoHunt[] {
  const g = parseInt(gmu, 10);
  if (Number.isNaN(g)) return [];
  return (IDAHO_DRAW[speciesKey] || []).filter((h) => parseInt(h.area, 10) === g);
}
`;

writeFileSync(new URL('../app/api/strategy/idahoDraw.ts', import.meta.url), body);
const totalHunts = Object.values(out).reduce((n, a) => n + a.length, 0);
console.log(`Wrote ${totalHunts} hunts → app/api/strategy/idahoDraw.ts`);
