// Builds the Idaho GMU "basics" dataset: every Game Management Unit's centroid,
// elk zone, and a geo description — emitted to app/api/strategy/idahoUnits.ts.
//
// "Basics first" for the multi-state pipeline: this gives Idaho units real
// coordinates (so the brief's access grounding stops falling back to a Wyoming
// coordinate) and a geo anchor, ahead of full controlled-hunt draw-odds work.
//
// Source: Idaho Fish & Game Game Units layer (authoritative GMU boundaries).
// Run: node scripts/buildIdahoUnits.mjs
import { writeFileSync } from 'node:fs';

const QUERY = 'https://gisportal-idfg.idaho.gov/hosting/rest/services/Hunting/MapServer/3/query';

const params = new URLSearchParams({
  where: '1=1',
  outFields: 'NAME,Elk_Zone',
  returnGeometry: 'true',
  outSR: '4326',
  geometryPrecision: '5',
  maxAllowableOffset: '0.004', // generalize — we only need centroids
  f: 'geojson',
});

console.log('Fetching Idaho GMUs from IDFG…');
const res = await fetch(`${QUERY}?${params}`);
if (!res.ok) { console.error('IDFG request failed:', res.status); process.exit(1); }
const gj = await res.json();
const feats = gj.features || [];
console.log(`Got ${feats.length} GMU features.`);

// Accumulate a bounding box per unit NAME (units may be multi-part).
const acc = new Map();
const walk = (c, bb) => {
  if (Array.isArray(c) && typeof c[0] === 'number') {
    const [lng, lat] = c;
    if (lat < bb.s) bb.s = lat; if (lat > bb.n) bb.n = lat;
    if (lng < bb.w) bb.w = lng; if (lng > bb.e) bb.e = lng;
  } else if (Array.isArray(c)) {
    c.forEach((x) => walk(x, bb));
  }
};

for (const f of feats) {
  const name = String(f.properties?.NAME ?? '').trim();
  if (!name) continue;
  const zone = String(f.properties?.Elk_Zone ?? '').trim();
  if (!acc.has(name)) acc.set(name, { zone, bb: { s: 90, w: 180, n: -90, e: -180 } });
  const entry = acc.get(name);
  if (!entry.zone && zone) entry.zone = zone;
  if (f.geometry?.coordinates) walk(f.geometry.coordinates, entry.bb);
}

const units = {};
for (const [name, { zone, bb }] of [...acc.entries()].sort((a, b) => a[0].localeCompare(b[0], undefined, { numeric: true }))) {
  if (bb.s > bb.n) continue; // no geometry
  const lat = +((bb.s + bb.n) / 2).toFixed(5);
  const lng = +((bb.w + bb.e) / 2).toFixed(5);
  units[name] = {
    unit: name,
    elkZone: zone || null,
    coords: { lat, lng },
    description: zone
      ? `Idaho Game Management Unit ${name}, in the ${zone} elk zone.`
      : `Idaho Game Management Unit ${name}.`,
  };
}

const body = `// AUTO-GENERATED by scripts/buildIdahoUnits.mjs — do not edit by hand.
// Idaho GMU "basics": centroid + elk zone + geo description for every unit.
// Source: Idaho Fish & Game Game Units GIS. Re-run the script to refresh.

export type IdahoUnit = {
  unit: string;
  elkZone: string | null;
  coords: { lat: number; lng: number };
  description: string;
};

export const IDAHO_GMU_UNITS: Record<string, IdahoUnit> = ${JSON.stringify(units, null, 2)};
`;

const outPath = new URL('../app/api/strategy/idahoUnits.ts', import.meta.url);
writeFileSync(outPath, body);
console.log(`Wrote ${Object.keys(units).length} Idaho units → app/api/strategy/idahoUnits.ts`);
