// Ingests Colorado big-game draw difficulty from CPW's "Post Draw Recap" PDFs
// into app/api/strategy/coloradoDraw.ts.
//
// CPW publishes draw data ONLY as dense PDFs (no API/table — confirmed across
// their whole GIS org). The exact preference-points-to-draw lives in a grouped
// matrix that doesn't parse reliably, so we extract the trustworthy signal: per
// hunt code, the CHOICE-1 DRAW SUCCESS % (resident / non-resident) plus the unit
// (decoded from the hunt code). This is a difficulty rate, NOT exact points.
//
// Requires `pdftotext` (xpdf/poppler) on PATH. Run: node scripts/buildColoradoDraw.mjs
import { writeFileSync, readFileSync, existsSync, statSync } from 'node:fs';
import { execSync } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';

const UA = { 'User-Agent': 'Mozilla/5.0 (huntengine-app ingestion)' };

// app speciesKey → CPW statistics page (we resolve the recap PDF link from it,
// so this survives the yearly filename change).
const SPECIES = {
  ELK: 'https://cpw.state.co.us/activities/hunting/big-game/hunting-elk/elk-statistics',
  DEER: 'https://cpw.state.co.us/activities/hunting/big-game/hunting-deer/deer-statistics',
  ANTELOPE: 'https://cpw.state.co.us/activities/hunting/big-game/hunting-pronghorn/pronghorn-statistics',
  MOOSE: 'https://cpw.state.co.us/activities/hunting/big-game/hunting-moose/moose-statistics',
  MTNGOAT: 'https://cpw.state.co.us/activities/hunting/big-game/hunting-mountain-goat/mountain-goat-statistics',
};

async function text(url) {
  const r = await fetch(url, { headers: UA });
  if (!r.ok) throw new Error(`${url} → ${r.status}`);
  return r.text();
}

// Stats page → recap share link → asset content id → direct original PDF URL.
async function resolveRecapPdf(statsUrl) {
  const page = await text(statsUrl);
  const share = (page.match(/https:\/\/cpw\.widen\.net\/s\/[a-z0-9]+\/postdrawrecapreport[a-z0-9_-]*/i) || [])[0];
  if (!share) throw new Error('no recap link on stats page');
  const sp = await text(share);
  const cid = (sp.match(/\/content\/([a-z0-9]+)\/png\//i) || [])[1];
  if (!cid) throw new Error('no asset content id');
  const name = share.split('/').pop();
  const year = (name.match(/-(\d{2})_/) || [])[1];
  return { url: `https://cpw.widen.net/content/${cid}/original/${name}.pdf`, year: year ? 2000 + +year : null };
}

// One hunt code per page. The "Total Choice 1" line carries the choice-1
// applicants then the success %s (res, non-res). Column count varies, so take
// the first number after the label as applicants and the first two % tokens as
// resident / non-resident success.
function parseRecap(txt) {
  const hunts = [];
  for (const pg of txt.split('\f')) {
    const lines = pg.split('\n').map((l) => l.replace(/\s+/g, ' ').trim());
    const code = lines.find((l) => /^[A-Z]{2}\d{3}[A-Z0-9]{2,}$/.test(l));
    if (!code) continue;
    const unit = parseInt(code.slice(2, 5), 10);
    if (Number.isNaN(unit)) continue;
    const norm = lines.join(' ');
    const ci = norm.indexOf('Total Choice 1');
    if (ci < 0) continue;
    const after = norm.slice(ci + 14);
    const apps = (after.match(/(\d+)/) || [])[1];
    const pcts = [...after.matchAll(/(\d+)%/g)].map((m) => +m[1]);
    if (pcts.length >= 2) {
      hunts.push({ code, unit, apps: apps ? +apps : null, resSuccessPct: pcts[0], nonResSuccessPct: pcts[1] });
    }
  }
  return hunts;
}

let dataYear = null;
const out = {};
for (const [key, statsUrl] of Object.entries(SPECIES)) {
  try {
    const { url, year } = await resolveRecapPdf(statsUrl);
    if (year) dataYear = year;
    const tmpPdf = path.join(os.tmpdir(), `co_${key}.pdf`);
    // Cache downloads so re-runs (e.g. to tweak the scout dataset shape) are fast.
    let buf;
    if (existsSync(tmpPdf) && statSync(tmpPdf).size > 1e6) {
      buf = readFileSync(tmpPdf);
    } else {
      buf = Buffer.from(await (await fetch(url, { headers: UA })).arrayBuffer());
      writeFileSync(tmpPdf, buf);
    }
    const tmpTxt = tmpPdf.replace(/\.pdf$/, '.txt');
    // pdftotext writes to the file; ignore its (noisy) stdio and don't let
    // warning spam overflow the exec buffer.
    execSync(`pdftotext -q -layout "${tmpPdf}" "${tmpTxt}"`, { stdio: 'ignore', maxBuffer: 1 << 28 });
    const hunts = parseRecap(readFileSync(tmpTxt, 'utf8'));
    out[key] = hunts.sort((a, b) => a.unit - b.unit || a.code.localeCompare(b.code));
    console.log(`${key}: ${(buf.length / 1e6).toFixed(1)}MB pdf → ${hunts.length} hunt codes (${[...new Set(hunts.map((h) => h.unit))].length} units)`);
  } catch (e) {
    console.error(`${key} failed:`, e.message);
    out[key] = [];
  }
}

const body = `// AUTO-GENERATED by scripts/buildColoradoDraw.mjs — do not edit by hand.
// Colorado big-game DRAW SUCCESS RATES (${dataYear ?? ''}) from CPW Post Draw Recap PDFs.
// Per hunt code: choice-1 draw success % (resident / non-resident) + unit.
// NOTE: this is a draw-success RATE, not exact preference-points-to-draw (CPW
// only publishes that in an unparseable grouped matrix).

export type ColoradoHunt = {
  code: string;            // CPW hunt code
  unit: number;            // GMU (decoded from the hunt code)
  apps: number | null;     // choice-1 applicants
  resSuccessPct: number;   // resident choice-1 draw success %
  nonResSuccessPct: number;
};

export const COLORADO_DRAW_YEAR = ${dataYear ?? 'null'};

export const COLORADO_DRAW: Record<string, ColoradoHunt[]> = ${JSON.stringify(out, null, 1)};

export function coloradoHuntsForUnit(speciesKey: string, unit: string): ColoradoHunt[] {
  const u = parseInt(unit, 10);
  if (Number.isNaN(u)) return [];
  return (COLORADO_DRAW[speciesKey] || []).filter((h) => h.unit === u);
}

// Scout dataset: aggregated per GMU (SCOUT recommends units, and a per-hunt-code
// list would blow the token budget). Each unit carries its hunt codes and the
// resident / non-resident choice-1 draw-success ranges + best (easiest) rate.
export function buildColoradoScoutDataset(speciesKey: string): Array<Record<string, unknown>> {
  const byUnit: Record<string, ColoradoHunt[]> = {};
  for (const h of COLORADO_DRAW[speciesKey] || []) {
    (byUnit[h.unit] = byUnit[h.unit] || []).push(h);
  }
  return Object.entries(byUnit).map(([unit, hunts]) => {
    const res = hunts.map((h) => h.resSuccessPct);
    const nr = hunts.map((h) => h.nonResSuccessPct);
    return {
      unit,
      huntCodes: hunts.slice(0, 6).map((h) => h.code),
      huntCount: hunts.length,
      resDrawSuccess: \`\${Math.min(...res)}-\${Math.max(...res)}%\`,
      nonResDrawSuccess: \`\${Math.min(...nr)}-\${Math.max(...nr)}%\`,
      bestResSuccess: Math.max(...res),
      bestNonResSuccess: Math.max(...nr),
    };
  });
}
`;

writeFileSync(new URL('../app/api/strategy/coloradoDraw.ts', import.meta.url), body);
const total = Object.values(out).reduce((n, a) => n + a.length, 0);
console.log(`Wrote ${total} CO hunt codes → app/api/strategy/coloradoDraw.ts`);
